from playwright.sync_api import sync_playwright
from pathlib import Path
import json
out=Path('/mnt/data/new_sx_web/verification');out.mkdir(exist_ok=True)
errors=[]
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 page=b.new_page(viewport={'width':1440,'height':1060},device_scale_factor=1)
 page.on('pageerror',lambda e:errors.append(str(e)))
 html=Path('/mnt/data/new_sx_web/PLAY.html').read_text()
 page.evaluate("Object.defineProperty(window,'localStorage',{value:{data:{},getItem(k){return this.data[k]??null},setItem(k,v){this.data[k]=v},removeItem(k){delete this.data[k]}}})")
 page.set_content(html,wait_until='domcontentloaded')
 page.screenshot(path=str(out/'desktop-cover.png'),full_page=True)
 page.locator('[data-action="fates"]').click()
 page.locator('[data-action="fate"]').first.click()
 page.locator('[data-action="start"]').click()
 page.screenshot(path=str(out/'desktop-map.png'),full_page=True)
 print(page.title(),page.locator('.map-node.available').count(),'reachable nodes')
 page.locator('.map-node.available').first.click()
 page.locator('[data-action="pause"]').click()
 page.screenshot(path=str(out/'desktop-battle.png'),full_page=True)
 page.locator('[data-action="skip"]').click()
 page.locator('[data-action="finishBattle"]').click()
 page.screenshot(path=str(out/'desktop-reward.png'),full_page=True)
 page.locator('[data-action="skipReward"]').click()
 page.locator('.map-node.available').first.click()
 page.screenshot(path=str(out/'desktop-event.png'),full_page=True)
 for w,h in [(375,667),(390,844),(414,896),(430,932),(750,1334)]:
  page.set_viewport_size({'width':w,'height':h})
  overflow=page.evaluate('document.documentElement.scrollWidth > innerWidth')
  print(w,h,'overflow',overflow)
  if overflow:errors.append(f'horizontal overflow at {w}x{h}')
  if w==390:page.screenshot(path=str(out/'mobile-event.png'),full_page=True)
 page.locator('[data-action="event"]').first.click()
 if page.locator('[data-action="cancelReplacement"]').count():page.locator('[data-action="cancelReplacement"]').click()
 page.locator('[data-action="leaveEvent"]').click()
 page.set_viewport_size({'width':390,'height':844})
 page.screenshot(path=str(out/'mobile-map.png'),full_page=True)
 before=page.evaluate("JSON.parse(localStorage.getItem('fengshen-run-v1'))")
 page.evaluate("const root=document.querySelector('fengshen-game');root.remove();const next=document.createElement('fengshen-game');document.body.append(next)")
 page.locator('[data-action="resume"]').click()
 after=page.evaluate("JSON.parse(localStorage.getItem('fengshen-run-v1'))")
 assert before==after,'Refresh modified save'
 page.locator('[data-action="tab"][data-id="build"]').last.click()
 page.screenshot(path=str(out/'mobile-build.png'),full_page=True)
 b.close()
(out/'browser-smoke.json').write_text(json.dumps({'errors':errors,'remountSaveExact':before==after,'renderer':'Chromium set_content (local URL navigation denied by browser policy); in-memory Storage adapter' },indent=2))
print('errors:',errors)
