import {Game,fateOptions,SLOT_ORDER} from '../build/engine.js';
export function score(g,id,rank=0){const a=g.ability(id),aff=g.c.origins.find(o=>o.id===g.s.origin).affinity;return (a.tags.includes(aff)?10:0)+(a.rarity==='mythic'?18:a.rarity==='rare'?3:0)+rank*4+Object.values(a.stats).reduce((sum,v)=>sum+(Array.isArray(v)?v[rank]:v)*.35,0); }
export function gain(g,id){const a=g.ability(id),eq=g.s.slots.find(x=>x?.id===id);if(eq)return eq.rank<3?7:-999;const matching=SLOT_ORDER.map((k,i)=>k===a.slot?i:-1).filter(i=>i>=0);if(matching.some(i=>!g.s.slots[i]))return 20+score(g,id);return score(g,id)-Math.min(...matching.map(i=>score(g,g.s.slots[i].id,g.s.slots[i].rank)));}
function eventValue(g,info){const ch=info.choice,hp=g.s.hp/g.stats().hp;let v=(info.chance??60)/20;for(const e of ch.effects??[])v+=e.type==='heal'?(hp<.8?40:8):e.type==='modify_stat'?e.stat==='attack'?15:e.stat==='defense'?18:4:e.type==='gain_xp'?5:e.type==='damage'?-15:e.type==='gain_currency'?6:0;if(ch.grant?.id)v+=Math.max(0,gain(g,ch.grant.id));else if(ch.grant)v+=10;return v;}
export function step(g){const s=g.s,c=g.c,hp=s.hp/g.stats().hp;
 if(s.pending){const p=s.pending,a=g.ability(p.id),candidates=SLOT_ORDER.map((k,i)=>k===a.slot?i:-1).filter(i=>i>=0).sort((i,j)=>score(g,s.slots[i].id,s.slots[i].rank)-score(g,s.slots[j].id,s.slots[j].rank));if(gain(g,p.id)>0)g.replace(candidates[0]);else{g.cancelReplacement();if(s.phase==='reward')g.skipReward();else if(s.phase==='shop')g.leaveShop();}return;}
 switch(s.phase){case 'map':{const weight={combat:3,event:9,hidden:10,rest:hp<.85?20:7,shop:s.gold>=25&&hp<.75?15:4,elite:hp>.8?12:1,major:10,boss:10};g.enter(g.available().sort((a,b)=>(weight[b.type]??0)-(weight[a.type]??0))[0].id);break;}case 'battle':g.finishBattle();break;case 'reward':{const ix=s.reward.map((id,i)=>({i,v:gain(g,id)})).sort((a,b)=>b.v-a.v)[0];if(ix?.v>0)g.reward(ix.i);else g.skipReward();break;}case 'shop':{const offers=s.stock.map((o,i)=>({i,v:o.sold||o.price>s.gold?-999:o.kind==='heal'?(hp<.85?50:-1):o.kind==='stat'?12:gain(g,o.id)})).sort((a,b)=>b.v-a.v);if(offers[0]?.v>0)g.buy(offers[0].i);else g.leaveShop();break;}case 'rest':if(hp<.86)g.rest('heal');else{const eq=s.slots.map((x,i)=>({x,i})).filter(o=>o.x&&o.x.rank<3).sort((a,b)=>score(g,b.x.id)-score(g,a.x.id))[0];if(eq)g.rest(g.ability(eq.x.id).slot==='artifact'?'artifact':'skill',eq.i);else g.rest('temper',0);}break;case 'event':{const opts=g.eventChoices().filter(x=>x.legal).map(x=>({x,v:eventValue(g,x)})).sort((a,b)=>b.v-a.v);if(!opts.length)throw new Error('No legal event choice');g.chooseEvent(opts[0].x.choice.id);break;}case 'event_result':g.leaveEvent();break;case 'ending':g.chooseEnding(g.legalEndings()[0].id);break;}
}
export function run(c,origin,seed,max=400){const fate=fateOptions(c,seed).sort((a,b)=>Object.keys(b.percent??{}).length-Object.keys(a.percent??{}).length)[0],g=Game.create(c,seed,origin,fate.id,'Sim');let decisions=0;while(!['dead','finished'].includes(g.s.phase)&&decisions++<max)step(g);if(decisions>=max)throw new Error('Non-terminating run');return g;}
