import { lstat, mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import {
  DOCS_ROOT,
  CONTENT_VERSION,
  METHOD_IDS,
  ARTIFACT_IDS,
  STORYLINE_IDS,
  ENEMY_IDS,
  ACT_IDS,
} from './constants.mjs'
import { assertValidContent, validateLoadedContent } from './validator.mjs'

export const GENERATED_HEADER = `[//]: # (GENERATED BY tools/content-kit; DO NOT EDIT. content_version: ${CONTENT_VERSION})`

export const DOCUMENT_PATHS = Object.freeze([
  'INDEX.md',
  'RULES.md',
  'ACTS.md',
  ...METHOD_IDS.map((id) => `methods/${id}.md`),
  'artifacts/COMMON.md',
  'artifacts/RARE.md',
  'artifacts/LEGENDARY.md',
  ...Array.from({ length: 4 }, (_, index) => `events/ACT${index + 1}.md`),
  ...STORYLINE_IDS.map((id) => `storylines/${id}.md`),
  'storylines/INDEPENDENT.md',
  ...Array.from({ length: 4 }, (_, index) => `enemies/ACT${index + 1}.md`),
  'enemies/FINAL.md',
])

const DOCUMENT_PATH_SET = new Set(DOCUMENT_PATHS)

const rarityLabels = {
  common: '普通',
  rare: '稀有',
  legendary: '传奇',
}

const kindLabels = {
  C: '普通斗法',
  E: '普通事件',
  K: '核心事件',
  L: '精英斗法',
  S: '商店',
  R: '休整',
  B: '幕首领',
  F: '终局渡劫',
}

const fieldLabels = {
  A: '战斗综合增益',
  B: '基础预算',
  C: '普通斗法',
  D: '直接输出',
  E: '普通事件',
  F: '终局',
  H: '参考气血',
  J: '行旅换算',
  K: '核心事件',
  L: '精英斗法',
  P: '十五回合表现',
  R: '休整',
  S: '商店',
  U: '事件效用',
  amount: '数量',
  amount_per_stack: '每层数量',
  amount_ratio: '数量比例',
  attack: '攻击',
  attack_ratio: '攻击倍率',
  attack_ratio_by_phase: '分相攻击倍率',
  attack_ratio_per_paid_rage: '每点已付怒气攻击倍率',
  attack_ratio_per_segment: '每段攻击倍率',
  attack_ratio_per_shield: '每点护盾攻击倍率',
  attack_ratio_per_stack: '每层攻击倍率',
  attack_ratio_per_stack_add: '每层攻击倍率增量',
  attributes: '属性',
  base_cap: '基础上限',
  base_public_basic_gain: '公共普攻回怒',
  base_public_gain: '公共基础收益',
  base_public_round_end_gain: '公共轮尾回怒',
  basic_damage_ratio_add: '普攻伤害倍率增量',
  basic_rage_gain_bonus: '普攻回怒增量',
  cap: '上限',
  cap_ratio: '上限比例',
  category: '类别',
  chance: '概率',
  crit_rate: '暴击率',
  common_price: '普通价格参照',
  cancellation: '取消条件',
  condition: '条件',
  count: '次数',
  damage_from: '伤害取值',
  damage_kind: '伤害类型',
  damage_ratio: '伤害倍率',
  damage_ratio_add: '伤害倍率增量',
  damage_scope: '伤害范围',
  defense: '防御',
  defense_ratio: '防御倍率',
  description: '说明',
  duration: '持续范围',
  duration_policy: '持续规则',
  duration_rounds: '持续轮数',
  duration_rounds_add: '持续轮数增量',
  effect: '效果',
  effect_id: '效果 ID',
  effect_ids: '效果 ID',
  element: '属性类型',
  enemy_id: '敌人',
  event_id: '事件',
  failure_hp_floor: '失败血线',
  failure_outcome: '失败结果',
  failure_rewards: '失败奖励',
  fallback: '回退',
  flat: '固定值',
  floor: '下限',
  gross_U: '总效用',
  heal_from: '治疗取值',
  hp: '气血',
  id: '标识',
  initial: '初始值',
  initial_coins: '初始灵石',
  index: '幕序',
  limit: '限制',
  max: '最大值',
  max_hp: '最大气血',
  max_hp_ratio: '最大气血倍率',
  max_hp_ratio_add: '最大气血倍率增量',
  max_stacks: '最大层数',
  mechanic: '专属机制',
  measured: '实测',
  method: '功法',
  min: '最小值',
  minimum_cap: '最低上限',
  mode: '模式',
  multiplier: '倍率',
  n: '境界层',
  name: '名称',
  node_budget: '节点预算',
  nodes: '节点',
  node_types: '节点类型',
  operation: '操作',
  optional: '可选',
  opening: '开场值',
  outcome: '结果',
  params: '参数',
  percent: '百分比',
  phase: '相位',
  planned_per_run: '每局计划',
  pools: '获取池',
  P_by_tier: '各层表现目标',
  primary: '主属性',
  quick: '玩家摘要',
  ratio: '比例',
  ratio_add: '比例增量',
  rarity: '位阶',
  reduction: '减免',
  reduction_per_stack: '每层减免',
  reference: '出处引用',
  reference_hp: '参考气血',
  reference_hp_by_act: '各幕参考气血',
  resolution: '兑现',
  reward_shape: '奖励形态',
  reward_profile: '奖励档',
  rewards: '奖励',
  role: '定位',
  route: '路线',
  routes: '路线',
  scene: '场景',
  secondary: '次属性',
  segments: '段数',
  set_flags: '设置标记',
  shield_from: '护盾取值',
  shield_bonus_from: '护盾加成取值',
  shield_ratio_add: '护盾倍率增量',
  source: '来源',
  source_id: '来源 ID',
  speed: '速度',
  stacks: '层数',
  stat: '属性',
  stat_focus: '属性侧重',
  status: '状态',
  summary: '摘要',
  scope: '范围',
  target: '目标',
  target_hp: '目标气血',
  text: '结算说明',
  tier: '层级',
  timing: '时机',
  tradeoff: '取舍',
  trigger: '触发',
  unique_group: '唯一组',
  value: '数值',
  victory_condition: '胜利条件',
  window: '观察轮数',
  xp: '修为',
  requirement: '前置条件',
  requirements: '前置条件',
}

const statusLabels = {
  poison: '中毒',
  burn: '燃烧',
  weakness: '虚弱',
  armor_break: '破甲',
}

const targetLabels = {
  self: '自身',
  enemy: '敌人',
  both: '双方',
  run: '本局',
}

const tierLabels = {
  normal: '普通',
  elite: '精英',
  boss: '首领',
  final: '终战',
}

const poolLabels = {
  common_artifact: '普通法宝池',
  rare_artifact: '稀有法宝池',
  legendary_artifact: '传奇法宝池',
  method_common: '普通功法池',
  method_rare: '稀有功法池',
  method_legendary: '传奇功法池',
  owned_methods: '已拥有功法',
}

const resourceLabels = {
  hp: '气血',
  coins: '灵石',
  xp: '修为',
}

const basisLabels = {
  flat: '固定值',
  reference_hp: '当前幕参考气血',
  common_price: '普通法宝价格参照',
  next_xp: '当前境界下一次完整突破需求',
}

const ratioBases = new Set(['reference_hp', 'common_price', 'next_xp'])

const talentCategoryLabels = {
  enhance: '强化',
  cycle: '循环',
  convert: '转化',
}

const attributeLabels = {
  attack: '攻击',
  defense: '防御',
  max_hp: '最大气血',
  crit_rate: '暴击率',
  speed: '速度',
}

const attributeFocusKeys = new Set([
  'primary',
  'secondary',
  'damage_from',
  'shield_from',
  'shield_bonus_from',
  'heal_from',
  'survival_from',
])

const operationLabels = {
  damage: '造成伤害',
  heal: '治疗',
  shield: '生成护盾',
  apply_status: '施加状态',
  modify_stat: '修改属性',
  modify_effect: '修改效果',
  rage_gain: '获得怒气',
  rage_cap: '修改怒气上限',
  rage_drain: '削减怒气',
  rage_drain_resist: '抵抗怒气削减',
  convert_overflow: '转化溢疗',
  consume_status: '消费状态',
  consume_shield: '消费护盾',
  advance_phase: '推进相位',
  grant_resource: '获得资源',
  prepare_next_battle: '准备下一场战斗',
  reduce_event_cost: '降低事件成本',
  replace_action: '替代动作',
  chance_damage: '概率伤害',
  modify_chance: '修改概率',
}

const triggerLabels = {
  battle_start: '战斗开始',
  basic_action: '普攻动作',
  rage_action: '怒技动作',
  basic_hit: '普攻命中',
  direct_hit: '直接命中',
  direct_crit: '直接暴击',
  action_end: '动作结束',
  enemy_action_end: '敌方动作结束',
  shield_absorbed: '护盾吸收伤害',
  shield_broken: '护盾破碎',
  heal_resolved: '治疗结算',
  overflow_resolved: '溢疗结算',
  dot_resolved: '持续伤害结算',
  round_end: '轮末',
  node_complete: '节点完成',
  battle_node_complete: '战斗节点完成',
  rest_complete: '休整完成',
  event_cost_paid: '事件成本支付',
  always: '始终',
}

const booleanLabels = {
  true: '是',
  false: '否',
}

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function fieldLabel(key) {
  return fieldLabels[key] ?? key
}

function numberText(value) {
  if (!Number.isFinite(value)) return '非有限数'
  return String(value)
}

function percentageText(value) {
  if (!Number.isFinite(value)) return '非有限数'
  const percentage = Math.round(value * 10000) / 100
  return `${numberText(percentage)}%`
}

function scalarText(value) {
  if (value === null || value === undefined) return '未填写'
  if (typeof value === 'number') return numberText(value)
  if (typeof value === 'boolean') return booleanLabels[String(value)]
  if (typeof value === 'string') {
    const trimmed = value.trim()
    return trimmed === '' ? '未填写' : trimmed
  }
  return String(value)
}

function createContext(entities = []) {
  const byId = new Map()
  const talents = new Map()
  for (const entity of entities) {
    if (typeof entity?.id === 'string') byId.set(entity.id, entity)
    if (entity?.kind === 'method') {
      for (const talent of entity.talents ?? []) {
        if (typeof talent?.id === 'string') talents.set(talent.id, { ...talent, method_id: entity.id })
      }
    }
  }
  return { byId, talents }
}

function readableId(value, context) {
  if (typeof value !== 'string') return scalarText(value)
  const entity = context?.byId?.get(value)
  if (entity?.name) return `${scalarText(entity.name)}（${code(value)}）`
  const talent = context?.talents?.get(value)
  if (talent?.name) return `${scalarText(talent.name)}（${code(value)}）`
  return scalarText(value)
}

function structuredText(value, key = '', context = undefined) {
  if (value === null || value === undefined) return '未填写'
  if (Array.isArray(value)) {
    if (value.length === 0) return '无'
    return value.map((item) => structuredText(item, key, context)).join('、')
  }
  if (isRecord(value)) {
    const parts = Object.entries(value)
      .filter(([, child]) => child !== undefined)
      .map(([childKey, child]) => `${fieldLabel(childKey)}=${structuredText(child, childKey, context)}`)
    return parts.length > 0 ? parts.join('；') : '无'
  }
  if (typeof value === 'string') {
    if (context?.byId?.has(value) || context?.talents?.has(value)) return readableId(value, context)
    if (key === 'fallback' && value === 'ordinary_event') return '普通事件'
    if (key === 'resource' || key === 'fallback') return resourceLabels[value] ?? scalarText(value, key)
    if (key === 'basis') return basisLabels[value] ?? scalarText(value, key)
    if (key === 'category') return talentCategoryLabels[value] ?? scalarText(value, key)
    if (key === 'operation') return operationLabels[value] ?? scalarText(value, key)
    if (key === 'trigger') return triggerLabels[value] ?? scalarText(value, key)
    if (key === 'target') return targetLabels[value] ?? scalarText(value, key)
    if (key === 'status' || key === 'owner_status' || key === 'enemy_status') return statusLabels[value] ?? scalarText(value, key)
    if (key === 'tier') return tierLabels[value] ?? scalarText(value, key)
    if (key === 'pool') return poolLabels[value] ?? scalarText(value, key)
  }
  return scalarText(value, key)
}

function line(value, context = undefined) {
  return structuredText(value, '', context)
    .replaceAll('\n', ' ')
    .replaceAll('<br/>', '；')
    .replaceAll('<br />', '；')
    .replaceAll('<br>', '；')
    .trim()
}

function table(value, context = undefined) {
  return line(value, context).replaceAll('|', '\\|')
}

function list(values, context = undefined) {
  if (!Array.isArray(values) || values.length === 0) return '无'
  return values.map((value) => {
    if (typeof value === 'string' && (context?.byId?.has(value) || context?.talents?.has(value))) {
      return readableId(value, context)
    }
    if (kindLabels[value]) return kindLabels[value]
    return line(value, context)
  }).join('、')
}

function code(value) {
  return `\`${table(value)}\``
}

function link(label, relativePath) {
  return `[${label}](${relativePath})`
}

function navigation(base) {
  const prefix = base === '.' ? './' : `${base}/`
  return `- ${link('内容首页', `${prefix}INDEX.md`)}；${link('共用规则', `${prefix}RULES.md`)}；${link('幕结构基线', `${prefix}ACTS.md`)}`
}

function header(title, intro = '', base = '.') {
  return [
    GENERATED_HEADER,
    `# ${title}`,
    '',
    intro,
    '',
    navigation(base),
  ].join('\n')
}

function attributesText(attributes) {
  if (!attributes) return '未填写'
  const parts = []
  for (const [key, value] of Object.entries(attributes.flat ?? {})) {
    parts.push(`${fieldLabel(key)} +${scalarText(value)}`)
  }
  for (const [key, value] of Object.entries(attributes.percent ?? {})) {
    parts.push(`${fieldLabel(key)} +${scalarText(value * 100)}%`)
  }
  return parts.length > 0 ? parts.join('；') : '无基础属性'
}

function effectText(effect, context) {
  if (!isRecord(effect)) return '效果记录未填写'
  const parts = [
    code(effect.id),
    line(effect.text, context),
    `操作：${operationLabels[effect.operation] ?? line(effect.operation, context)}`,
    `触发：${triggerLabels[effect.trigger] ?? line(effect.trigger, context)}`,
    `目标：${structuredText(effect.target, 'target', context)}`,
    `参数：${structuredText(effect.params, 'params', context)}`,
  ]
  if (Array.isArray(effect.requires) && effect.requires.length > 0) parts.push(`前置：${list(effect.requires, context)}`)
  if (Array.isArray(effect.consumes) && effect.consumes.length > 0) parts.push(`消费：${list(effect.consumes, context)}`)
  if (Array.isArray(effect.replaces) && effect.replaces.length > 0) parts.push(`替代：${list(effect.replaces, context)}`)
  if (isRecord(effect.limit)) parts.push(`限制：${structuredText(effect.limit, 'limit', context)}`)
  return parts.join('；')
}

function playerEffectText(effect, context) {
  const text = line(effect?.text, context)
  return text.replace(
    /(?:(当前幕|当前)?参考气血)\s*(0?\.\d+|\d+(?:\.\d+)?)\s*倍/g,
    (_match, _scope, ratio) => `${basisLabels.reference_hp}的${percentageText(Number(ratio))}`,
  )
}

function effectLines(effects, context) {
  if (!Array.isArray(effects) || effects.length === 0) return ['- 开发效果：无']
  return effects.map((effect) => `- ${effectText(effect, context)}`)
}

function effectSection(effects, title = '开发效果', context = undefined) {
  return [
    '',
    `::: details ${title}`,
    ...effectLines(effects, context),
    ':::',
  ].join('\n')
}

function effectSummaryLines(effects, context) {
  if (!Array.isArray(effects) || effects.length === 0) return ['- 无']
  return effects.map((effect) => `- ${playerEffectText(effect, context)}`)
}

function targetText(target, context = undefined) {
  return structuredText(target, 'target', context)
}

function amountWithBasis(amount, basis) {
  const basisText = basisLabels[basis] ?? scalarText(basis)
  const amountText = ratioBases.has(basis) && typeof amount === 'number'
    ? percentageText(amount)
    : scalarText(amount)
  return `${amountText}（${basisText}）`
}

function costText(costs, context) {
  if (!Array.isArray(costs) || costs.length === 0) return '无'
  return costs.map((cost) => {
    if (!isRecord(cost)) return line(cost, context)
    if (cost.type === 'resource') {
      const resource = resourceLabels[cost.resource] ?? scalarText(cost.resource)
      const survive = cost.must_survive ? '，支付后须存活' : ''
      return `${resource} ${amountWithBasis(cost.amount, cost.basis)}${survive}`
    }
    return line(cost, context)
  }).join('；')
}

function readableArtifact(id, context) {
  return readableId(id, context)
}

function readableMethod(id, context) {
  return readableId(id, context)
}

function rewardText(rewards, context) {
  if (!Array.isArray(rewards) || rewards.length === 0) return '无'
  return rewards.map((reward) => {
    if (!isRecord(reward)) return line(reward, context)
    if (reward.type === 'artifact') return `${readableArtifact(reward.id, context)} ×${scalarText(reward.count)}`
    if (reward.type === 'resource') {
      const resource = resourceLabels[reward.resource] ?? scalarText(reward.resource)
      return `${resource} ${amountWithBasis(reward.amount, reward.basis)}`
    }
    if (reward.type === 'pool') return `${poolLabels[reward.pool] ?? scalarText(reward.pool)} ×${scalarText(reward.count)}`
    if (reward.type === 'method') return `功法 ${readableMethod(reward.id, context)}`
    if (reward.type === 'preparation') {
      return `战前准备：${fieldLabel(reward.effect)} ${amountWithBasis(reward.amount, reward.basis)}`
    }
    if (reward.type === 'swap_method') return '交换已拥有功法'
    return line(reward, context)
  }).join('；')
}

function requirementText(requirements, context) {
  if (!Array.isArray(requirements) || requirements.length === 0) return '无'
  return requirements.map((requirement) => {
    if (!isRecord(requirement)) return line(requirement, context)
    if (requirement.type === 'can_pay') return '灵石足够支付'
    if (requirement.type === 'capacity') {
      return `${readableArtifact(requirement.id, context)}可容纳 ${scalarText(requirement.count)} 层`
    }
    if (requirement.type === 'owned_artifact') {
      return `已持有 ${readableArtifact(requirement.id, context)} ×${scalarText(requirement.count)}`
    }
    if (requirement.type === 'known_method') return `已知功法 ${readableMethod(requirement.id, context)}`
    if (requirement.type === 'flag') return `已具备标记 ${scalarText(requirement.id)}=${scalarText(requirement.value)}`
    return line(requirement, context)
  }).join('；')
}

function routeNode(node, context) {
  if (typeof node === 'string') {
    if (kindLabels[node]) return `${node} ${kindLabels[node]}`
    if (context?.byId?.has(node) || context?.talents?.has(node)) return readableId(node, context)
    if (/^R-/.test(node)) return `R ${kindLabels.R}节点（${code(node)}）`
    if (/^SHOP-/.test(node)) return `S ${kindLabels.S}节点（${code(node)}）`
    return scalarText(node)
  }
  if (!isRecord(node)) return line(node, context)
  const type = node.type ?? node.kind ?? node.node_type ?? ''
  const id = node.id ?? node.enemy_id ?? node.event_id ?? ''
  const typeLabel = kindLabels[type] ? `${type} ${kindLabels[type]}` : line(type, context)
  if (!id) return typeLabel
  if (context?.byId?.has(id) || context?.talents?.has(id)) return `${typeLabel}：${readableId(id, context)}`
  return `${typeLabel}：节点（${code(id)}）`
}

function routeNodes(nodes, context) {
  if (!Array.isArray(nodes)) return '未填写'
  return nodes.map((node) => routeNode(node, context)).join(' → ')
}

function actRoutes(routes) {
  if (Array.isArray(routes)) return routes
  if (routes && typeof routes === 'object') {
    return Object.entries(routes).map(([name, value]) => (
      Array.isArray(value) ? { name, nodes: value } : { name, ...(value ?? {}) }
    ))
  }
  return []
}

function detailObjectLines(value, context) {
  if (!isRecord(value)) return [`- ${line(value, context)}`]
  return Object.entries(value).map(([key, child]) => `- ${fieldLabel(key)}：${structuredText(child, key, context)}`)
}

function entityTitle(entity) {
  return line(entity?.name ?? entity?.id)
}

function entityDevId(entity) {
  return `- 开发标识：${code(entity?.id ?? '未填写')}`
}

function renderIndex(report) {
  const entities = report.model?.entities ?? []
  const byId = new Map(entities.map((entity) => [entity?.id, entity]))
  const methods = METHOD_IDS.map((id) => byId.get(id)).filter(Boolean)
  const artifacts = entities.filter((entity) => entity?.kind === 'artifact')
  const events = entities.filter((entity) => entity?.kind === 'event')
  const ordinaryEvents = events.filter((event) => event.event_type === 'ordinary')
  const coreEvents = events.filter((event) => event.event_type === 'core')
  const storylines = entities.filter((entity) => entity?.kind === 'storyline')
  const enemies = entities.filter((entity) => entity?.kind === 'enemy')
  const actEnemies = enemies.filter((enemy) => enemy.tier !== 'final')
  const finalEnemies = enemies.filter((enemy) => enemy.tier === 'final')
  const acts = entities.filter((entity) => entity?.kind === 'act')
  const talentCount = methods.reduce((total, method) => total + (method.talents?.length ?? 0), 0)
  const counts = report.counts ?? {}
  const entityLink = (id, relativePath, fallbackLabel = id) => {
    const entity = byId.get(id)
    const name = entity?.name ? line(entity.name) : fallbackLabel
    return link(`${name}（${id}）`, relativePath)
  }
  const methodLinks = methods.map((method) => entityLink(method.id, `./methods/${method.id}.md`))
  const artifactLinks = [
    link('普通法宝', './artifacts/COMMON.md'),
    link('稀有法宝', './artifacts/RARE.md'),
    link('传奇法宝', './artifacts/LEGENDARY.md'),
  ]
  const eventLinks = Array.from({ length: 4 }, (_, index) => (
    link(`第${index + 1}幕事件`, `./events/ACT${index + 1}.md`)
  ))
  const storylineLinks = STORYLINE_IDS.map((id) => entityLink(id, `./storylines/${id}.md`))
  const enemyLinks = [
    ...Array.from({ length: 4 }, (_, index) => link(`第${index + 1}幕敌人`, `./enemies/ACT${index + 1}.md`)),
    link('终战敌人', './enemies/FINAL.md'),
  ]
  return [
    header('山海版首发内容卡库', '本页由内容工具根据 YAML 清单生成，面向玩家阅读；数值是首轮设计输入，不代表已经实测或平衡。'),
    '',
    `- 内容版本：${code(CONTENT_VERSION)}`,
    '- 设计状态：`design_target`',
    '- 实测边界：所有记录要求 `balance.measured: null`；伤害、持续伤害、护盾、治疗、状态和怒气仍待运行时校准。',
    '',
    '## 数量',
    '',
    '| 类型 | 数量 | 阅读页 |',
    '| --- | ---: | --- |',
    `| 功法 | ${counts.methods ?? methods.length} 门 / ${talentCount} 天赋 | ${link('功法阅读入口', './methods/RKF01.md')} |`,
    `| 法宝 | ${counts.artifacts ?? artifacts.length} 件 / 3 页 | ${link('法宝阅读入口', './artifacts/COMMON.md')} |`,
    `| 事件 | ${ordinaryEvents.length || '36'} 普通 / ${coreEvents.length || '16'} 核心 | ${link('事件阅读入口', './events/ACT1.md')} |`,
    `| 故事线 | ${counts.storylines ?? storylines.length} 条人物线 + 4 项独立核心 | ${link('人物线阅读入口', './storylines/RS01.md')} |`,
    `| 敌人 | ${actEnemies.length || '32'} 套幕敌人 + ${finalEnemies.length || '2'} 套终战 | ${link('敌人阅读入口', './enemies/ACT1.md')} |`,
    `| 幕结构 | ${counts.acts ?? acts.length} 幕 | ${link('幕结构阅读入口', './ACTS.md')} |`,
    '',
    '## 32页阅读入口',
    '',
    '### 基础（3页）',
    '',
    `- ${link('内容首页', './INDEX.md')}`,
    `- ${link('共用规则', './RULES.md')}`,
    `- ${link('幕结构、路线与经济', './ACTS.md')}`,
    '',
    `### 功法（${methods.length || counts.methods || 10}页；${talentCount}天赋）`,
    '',
    ...methodLinks.map((entry) => `- ${entry}`),
    '',
    '### 法宝（3页）',
    '',
    ...artifactLinks.map((entry) => `- ${entry}`),
    '',
    `### 事件（4页；${ordinaryEvents.length || 36}普通 / ${coreEvents.length || 16}核心）`,
    '',
    ...eventLinks.map((entry) => `- ${entry}`),
    '',
    `### 人物线（${STORYLINE_IDS.length}条 + 独立核心）`,
    '',
    ...storylineLinks.map((entry) => `- ${entry}`),
    `- ${link('独立核心机缘（4项）', './storylines/INDEPENDENT.md')}`,
    '',
    '### 敌人（4幕 + 终战）',
    '',
    ...enemyLinks.map((entry) => `- ${entry}`),
    '',
    '## 边界',
    '',
    '内容只从显式 `manifest.yaml` 读取。玩家页展示选择所需的短文案、关键数值、成本、条件、三选一天赋树、敌人真实配装；开发详情只展开效果 ID 和结算语义，不把整段 YAML 当卡面。',
    '',
    '::: details 工具与验收说明',
    '- 缺少 manifest 清单文件、空文件、重复 ID、非法 YAML、非法引用或越界配装都会使 `validate` 失败。',
    '- `target` 是首测输入，`measured` 保持 `null`；通过结构校验不等于伤害或胜率已平衡。',
    '- 站点自动收录 docs/shanhai/ 内非隐藏 Markdown，不逐页登记，也不扫描整个仓库。',
    ':::',
    '',
  ].join('\n')
}

function renderRules(rules) {
  const statusEntries = Object.entries(rules?.statuses ?? {}).filter(([, status]) => isRecord(status))
  const statusNotes = Object.entries(rules?.statuses ?? {}).filter(([, status]) => !isRecord(status))
  const statuses = statusEntries.map(([name, status]) => (
    `| ${table(statusLabels[name] ?? name)} | ${table(status.max_stacks ?? '未设')} | ${table(status.duration_rounds ?? '未设')} | ${table(status.duration_policy ?? status.stat ?? '未设')} |`
  ))
  return [
    header('共用规则', '玩家先看：资源、属性、战斗窗口和状态的共同边界。具体卡面仍以功法、法宝、事件和敌人页为准。'),
    '',
    `- 属性：${list((rules?.attributes ?? []).map((attribute) => fieldLabel(attribute)))}`,
    `- 四幕预算：${targetText(rules?.adventure?.baseline)}`,
    `- 每幕节点：${scalarText(rules?.adventure?.nodes_per_act)}；终局节点：${scalarText(rules?.adventure?.terminal_nodes)}`,
    `- 怒气：上限 ${scalarText(rules?.rage?.base_cap)}，开场 ${scalarText(rules?.rage?.opening)}，普攻完成 +${scalarText(rules?.rage?.basic_completed)}`,
    '',
    '## 状态',
    '',
    '| 状态 | 上限 | 持续轮数 | 结算边界 |',
    '| --- | ---: | ---: | --- |',
    ...(statuses.length > 0 ? statuses : ['| 未填写 | 未设 | 未设 | 未设 |']),
    '',
    '::: details 状态与首测配置',
    ...(statusNotes.length > 0
      ? statusNotes.map(([name, value]) => `- ${statusLabels[name] ?? fieldLabel(name)}：${line(value)}`)
      : ['- 没有额外的状态文字边界。']),
    ...detailObjectLines(rules?.cultivation),
    ...detailObjectLines(rules?.adventure),
    ...detailObjectLines(rules?.economy),
    ':::',
    '',
    '## 首测参照',
    '',
    `- 观察轮数：${scalarText(rules?.combat?.observation_rounds)}；直接伤害防御常数：${scalarText(rules?.combat?.direct_defense_constant)}`,
    `- 普通 / 稀有 / 传奇法宝预算：${targetText(rules?.rarities)}`,
    `- 初始灵石：${scalarText(rules?.economy?.initial_coins)}；休整恢复：${scalarText(rules?.economy?.rest_heal_ratio)}；事件恢复：${scalarText(rules?.economy?.event_heal_ratio)}`,
    '',
    '::: details 开发详情',
    `- 伤害公式：${line(rules?.combat?.direct_damage_formula)}`,
    `- 伤害取整：${line(rules?.combat?.damage_rounding)}`,
    `- 毒与燃烧：${line(rules?.statuses?.dot_snapshot)}`,
    `- 校准声明：${line(rules?.calibration?.damage_and_status_values)}`,
    ':::',
    '',
  ].join('\n')
}

function renderActDetails(title, value, context) {
  return [
    `### ${title}`,
    ...(isRecord(value) ? detailObjectLines(value, context) : [`- ${line(value, context)}`]),
    '',
  ]
}

function renderActs(acts, context) {
  const rows = []
  for (const act of acts) {
    const final = act.id === 'RF01'
    rows.push(`## ${final ? '终局' : `第${act.index}幕`} ${entityTitle(act)}`)
    rows.push('')
    rows.push(entityDevId(act))
    rows.push(`- 主线目标：${line(act.story?.goal ?? act.story?.target ?? act.summary, context)}`)
    rows.push('')
    rows.push('### 节点预算')
    rows.push('')
    rows.push('| 节点 | 数量 |')
    rows.push('| --- | ---: |')
    for (const [type, count] of Object.entries(act.node_budget ?? {})) {
      rows.push(`| ${kindLabels[type] ?? type} | ${scalarText(count)} |`)
    }
    rows.push('')
    rows.push('### 路线')
    rows.push('')
    const routes = actRoutes(act.routes)
    if (routes.length === 0) {
      rows.push('- 未填写路线。')
    } else {
      for (const [index, route] of routes.entries()) {
        rows.push(`::: details ${line(route.name ?? route.id ?? `路线${index + 1}`, context)}`)
        rows.push(`- 节点：${routeNodes(route.nodes, context)}`)
        if (route.count) rows.push(`- 节点计数：${targetText(route.count)}`)
        rows.push(':::')
      }
    }
    rows.push('')
    rows.push('::: details 故事、奖励与投放')
    rows.push(...renderActDetails('故事与幕间', act.story, context))
    rows.push(...renderActDetails('奖励候选', Array.isArray(act.rewards) ? { items: rewardText(act.rewards, context) } : act.rewards, context))
    rows.push(...renderActDetails('内容池', act.pools, context))
    rows.push(':::')
    rows.push('')
    rows.push('::: details 经济、培养与幕间衔接')
    rows.push(...renderActDetails('经济', act.economy, context))
    rows.push(...renderActDetails('培养', act.cultivation, context))
    rows.push(...renderActDetails('幕间衔接', act.transition, context))
    rows.push(':::')
    rows.push('')
  }
  return [
    header('幕结构、路线与经济', '四幕各 11 个真实节点，终局只有一场 F；路线展示机会成本，不承诺胜率。'),
    '',
    ...rows,
    '::: details 开发边界',
    '- 普通斗法、事件内部战、核心对白和领奖确认不额外增加节点。',
    '- 终局 RF01 不追加法宝、商店、休整、免费突破或奖励包。',
    ':::',
    '',
  ].join('\n')
}

function talentTitle(talent) {
  return `${scalarText(talent?.tier)}层${scalarText(talent?.branch)}：${line(talent?.name)}`
}

function statFocusText(value) {
  if (Array.isArray(value)) {
    return value.map((item) => attributeLabels[item] ?? scalarText(item)).join('、')
  }
  if (!isRecord(value)) return attributeLabels[value] ?? structuredText(value, 'stat_focus')
  return Object.entries(value)
    .map(([key, child]) => {
      const valueText = attributeFocusKeys.has(key)
        ? statFocusText(child)
        : structuredText(child, key)
      return `${fieldLabel(key)}=${valueText}`
    })
    .join('；')
}

function renderMethod(method, context) {
  const talentRows = []
  for (let tier = 1; tier <= 4; tier += 1) {
    for (const branch of ['A', 'B', 'C']) {
      const talent = method.talents?.find((item) => item.tier === tier && item.branch === branch)
      const category = talentCategoryLabels[talent?.category] ?? line(talent?.category ?? '未填写')
      talentRows.push(`| ${tier} | ${branch} | ${table(talent?.name ?? '未填写')} | ${table(talent?.quick ?? '未填写')} | ${table(category)} |`)
    }
  }
  const lines = [
    header(entityTitle(method), line(method.summary, context), '..'),
    '',
    entityDevId(method),
    `- 位阶：${rarityLabels[method.rarity] ?? line(method.rarity)}`,
    `- 定位：${line(method.role, context)}`,
    `- 属性侧重：${statFocusText(method.stat_focus)}`,
    `- 专属机制：${method.mechanic === null ? '无' : structuredText(method.mechanic, 'mechanic', context)}`,
    `- 十五回合目标：${targetText(method.balance?.target?.P_by_tier, context)}`,
    '',
    '## 基础动作',
    '',
    `- **${line(method.actions?.basic?.name, context)}**：${line(method.actions?.basic?.quick, context)}`,
    `- **${line(method.actions?.rage?.name, context)}**：${line(method.actions?.rage?.quick, context)}`,
    effectSection(method.actions?.basic?.effects, '普攻开发详情', context),
    effectSection(method.actions?.rage?.effects, '怒技开发详情', context),
    '',
    '## 固有被动',
    '',
    ...effectSummaryLines(method.passives, context),
    '',
    '## 行旅能力',
    '',
    ...effectSummaryLines(method.travel, context),
    '',
    '## 天赋树',
    '',
    '| 层 | 分支 | 名称 | 玩家摘要 | 类别 |',
    '| ---: | :---: | --- | --- | --- |',
    ...talentRows,
    '',
    '## 天赋效果',
    '',
  ]
  for (const talent of method.talents ?? []) {
    lines.push(`::: details ${talentTitle(talent)}`)
    lines.push(`- 玩家摘要：${line(talent.quick, context)}`)
    lines.push(`- 类别：${talentCategoryLabels[talent.category] ?? line(talent.category, context)}`)
    lines.push(`- 开发标识：${code(talent.id)}`)
    lines.push(...effectLines(talent.effects, context))
    lines.push(':::')
  }
  lines.push(
    '',
    '## 推荐路线',
    '',
    '| 路线 | 说明 | 选择 |',
    '| --- | --- | --- |',
    ...(method.routes ?? []).map((route) => `| ${table(route.name, context)} | ${table(route.summary, context)} | ${list(route.talents, context)} |`),
    effectSection(method.passives, '战斗被动开发详情', context),
    effectSection(method.travel, '行旅效果开发详情', context),
    '',
  )
  return lines.join('\n')
}

function renderArtifacts(artifacts, rarity, context) {
  const pageTitle = `${rarityLabels[rarity]}法宝`
  const intro = rarity === 'common'
    ? '同名普通法宝按卡面上限叠层；属性与能力同时存在，取得后从下一个合法窗口起生效。'
    : '单件法宝展示属性、能力和预算；位阶不是境界，不保证每局出现。'
  const lines = [
    header(pageTitle, intro, '..'),
    '',
    '| 名称 | 属性 | 上限 | 预算 A/J/B |',
    '| --- | --- | ---: | --- |',
  ]
  for (const artifact of artifacts.filter((item) => item.rarity === rarity)) {
    const target = artifact.balance?.target ?? {}
    lines.push(`| ${table(artifact.name, context)} | ${table(attributesText(artifact.attributes), context)} | ${scalarText(artifact.max_stacks)} | ${table(`${scalarText(target.A)}/${scalarText(target.J)}/${scalarText(target.B)}`)} |`)
  }
  lines.push('')
  for (const artifact of artifacts.filter((item) => item.rarity === rarity)) {
    lines.push(`### ${entityTitle(artifact)}`)
    lines.push('')
    lines.push(entityDevId(artifact))
    lines.push(line(artifact.summary, context))
    lines.push('')
    lines.push(`- 玩家看到：${line(artifact.description, context)}`)
    lines.push(`- 获取池：${list(artifact.acquisition?.pools, context)}`)
    lines.push(`- 唯一组：${artifact.unique_group ? line(artifact.unique_group, context) : '无'}`)
    lines.push(effectSection(artifact.effects, '法宝开发效果', context))
    lines.push('')
  }
  lines.push('::: details 开发边界')
  lines.push('- `A` 是战斗综合增益目标，`J` 是旅途换算尺，`B = A/5 + J` 只用于设计分摊。')
  lines.push('- 基础属性、层数上限和卡面主值沿用 44 张既有定义；实测仍为空。')
  lines.push(':::')
  lines.push('')
  return lines.join('\n')
}

function renderOption(option, context) {
  const rewardLabel = option.encounter ? '胜利获得' : '获得'
  const lines = [
    `### ${line(option.label, context)}`,
    '',
    `- 玩家摘要：${line(option.quick, context)}`,
    `- 条件：${requirementText(option.requirements, context)}`,
    `- 成本：${costText(option.costs, context)}`,
    `- ${rewardLabel}：${rewardText(option.rewards, context)}`,
  ]
  if (option.encounter) {
    const encounter = option.encounter
    const enemy = context?.byId?.get(encounter.enemy_id)
    const enemyLabel = enemy ? `${entityTitle(enemy)}（${code(enemy.id)}）` : readableId(encounter.enemy_id, context)
    lines.push(`- 内部挑战：${enemyLabel}；模式：${line(encounter.mode, context)}`)
    lines.push(`- 胜利条件：${line(encounter.victory_condition ?? `击败${enemy?.name ?? encounter.enemy_id}`, context)}；胜利后兑现本项奖励。`)
    lines.push(`- 失败血线：${scalarText(encounter.failure_hp_floor)}；失败奖励：${rewardText(encounter.failure_rewards, context)}`)
    lines.push(`- 失败结果：${line(encounter.failure_outcome, context)}`)
  }
  lines.push(`- 结果：${line(option.outcome, context)}`)
  if (option.set_flags) lines.push(`- 标记变化：${targetText(option.set_flags, context)}`)
  lines.push('')
  return lines
}

function renderEventSettlement(event, context) {
  return [
    '::: details 结算开发详情',
    `- 事件效用目标（gross_U）：${targetText(event.balance?.target?.gross_U, context)}`,
    `- 一次性结算：${scalarText(event.settlement?.once)}；行旅触发：${scalarText(event.settlement?.travel_triggers)}；内部战斗包：${scalarText(event.settlement?.internal_battle_package)}`,
    `- 回退：${structuredText(event.settlement?.fallback, 'fallback', context)}`,
    ':::',
    '',
  ]
}

function renderEventOptions(event, context) {
  const lines = []
  for (const option of event.options ?? []) lines.push(...renderOption(option, context))
  return lines
}

function renderEvents(events, act, context) {
  const selected = events.filter((event) => event.acts?.includes(act))
  const lines = [
    header(`第${act}幕事件`, '事件占一个真实事件位；选项列出即时成本、条件和兑现边界，内部战不发通用战斗包。', '..'),
    '',
  ]
  for (const event of selected) {
    lines.push(`## ${entityTitle(event)}`)
    lines.push('')
    lines.push(entityDevId(event))
    lines.push(line(event.scene, context))
    lines.push('')
    lines.push(`- 类型：${event.event_type === 'core' ? '核心机缘' : '普通事件'}；允许幕：${list(event.acts)}`)
    lines.push('')
    lines.push(...renderEventOptions(event, context))
    lines.push(...renderEventSettlement(event, context))
  }
  return lines.join('\n')
}

function encounterId(value) {
  return typeof value === 'string' ? value : value?.id ?? value?.event_id ?? value?.event
}

function renderStoryline(storyline, events, context) {
  const lines = [
    header(entityTitle(storyline), line(storyline.premise, context), '..'),
    '',
    entityDevId(storyline),
    `- 人物：${line(storyline.character, context)}`,
    `- 计划：每局最多一条；未完成时不补发兑现奖励。`,
    '',
    '## 两次相遇',
    '',
  ]
  for (const [index, rawEncounter] of (storyline.encounters ?? []).entries()) {
    const id = encounterId(rawEncounter)
    const event = events.find((item) => item.id === id)
    lines.push(`### 第${index + 1}次：${event ? entityTitle(event) : readableId(id, context)}`)
    lines.push('')
    if (!event) {
      lines.push(`- 事件标识：${code(id ?? '未填写')}`)
      lines.push('- 事件内容未加载。')
      lines.push('')
      continue
    }
    lines.push(entityDevId(event))
    lines.push(`- 可出现幕：${list(event.acts)}`)
    lines.push(`- 场景：${line(event.scene, context)}`)
    lines.push('')
    lines.push(...renderEventOptions(event, context))
    lines.push(...renderEventSettlement(event, context))
  }
  lines.push(
    `- 承诺：${structuredText(storyline.commitment, 'commitment', context)}`,
    `- 兑现：${structuredText(storyline.resolution, 'resolution', context)}`,
    '',
    '::: details 开发详情',
    `- 选择规则：计划 ${scalarText(storyline.selection?.planned_per_run)} 条；可选：${scalarText(storyline.selection?.optional)}；回退：${structuredText(storyline.selection?.fallback, 'fallback', context)}`,
    ':::',
    '',
  )
  return lines.join('\n')
}

function renderIndependent(events, storylines, context) {
  const used = new Set(storylines.flatMap((storyline) => (storyline.encounters ?? []).map(encounterId)))
  const independent = events.filter((event) => !used.has(event.id))
  return [
    header('独立核心机缘', '核心事件中未被六条人物线占用的四项独立机缘；可绕过，不是通关门槛。', '..'),
    '',
    ...independent.flatMap((event) => [
      `## ${entityTitle(event)}`,
      '',
      entityDevId(event),
      line(event.scene, context),
      '',
      `- 可出现幕：${list(event.acts)}`,
      '',
      ...renderEventOptions(event, context),
      ...renderEventSettlement(event, context),
    ]),
    '::: details 开发边界',
    '- 独立核心数量固定为 4；核心内部战不复制普通斗法资源包，也不增加节点。',
    ':::',
    '',
  ].join('\n')
}

function renderEnemyLoadout(enemy, context) {
  const artifacts = (enemy.artifacts ?? []).map((artifact) => `${readableArtifact(artifact.id, context)} ×${scalarText(artifact.stacks)}`)
  const talents = (enemy.talents ?? []).map((talent) => readableId(talent, context))
  return {
    artifacts: artifacts.length > 0 ? artifacts.join('、') : '无',
    talents: talents.length > 0 ? talents.join('、') : '无',
  }
}

function renderEnemies(enemies, act, context) {
  const selected = enemies.filter((enemy) => enemy.id.startsWith(`EN-A${act}-`))
  const lines = [
    header(`第${act}幕敌人`, '敌情预览免费公开完整功法、天赋、法宝和压力标签；敌方配装不等于掉落。', '..'),
    '',
  ]
  for (const enemy of selected) {
    const loadout = renderEnemyLoadout(enemy, context)
    lines.push(`## ${entityTitle(enemy)}`)
    lines.push('')
    lines.push(entityDevId(enemy))
    lines.push(line(enemy.identity, context))
    lines.push('')
    lines.push(`- 档位：${tierLabels[enemy.tier] ?? line(enemy.tier, context)}；功法：${readableMethod(enemy.method, context)}；境界层：n${scalarText(enemy.n)}`)
    lines.push(`- 属性：${attributesText({ flat: enemy.stats, percent: {} })}`)
    lines.push(`- 压力：${list(enemy.pressure, context)}`)
    lines.push(`- 战前选择：${list(enemy.counterplay, context)}`)
    lines.push(`- 法宝：${loadout.artifacts}`)
    lines.push(`- 天赋：${loadout.talents}`)
    lines.push('')
    lines.push('::: details 敌方开发详情')
    lines.push(`- 预览：${line(enemy.preview, context)}`)
    lines.push(`- 阶段：${enemy.phases?.length ? enemy.phases.map((phase) => line(phase.name ?? phase.id ?? phase.source ?? '已声明来源', context)).join('、') : '无额外阶段'}`)
    lines.push(`- 奖励档：${tierLabels[enemy.reward_profile] ?? line(enemy.reward_profile, context)}；实测仍为空。`)
    lines.push(':::')
    lines.push('')
  }
  return lines.join('\n')
}

function renderFinalEnemies(enemies, context) {
  return [
    header('终战敌人', '终局只有一场 F；两种候选均不提供新法宝、商店、休整或通用奖励。', '..'),
    '',
    ...enemies.filter((enemy) => enemy.tier === 'final').flatMap((enemy) => {
      const loadout = renderEnemyLoadout(enemy, context)
      return [
        `## ${entityTitle(enemy)}`,
        '',
        entityDevId(enemy),
        line(enemy.identity, context),
        '',
        `- 功法：${readableMethod(enemy.method, context)}；境界层：n${scalarText(enemy.n)}`,
        `- 属性：${attributesText({ flat: enemy.stats, percent: {} })}`,
        `- 压力：${list(enemy.pressure, context)}`,
        `- 战前选择：${list(enemy.counterplay, context)}`,
        `- 法宝：${loadout.artifacts}`,
        `- 天赋：${loadout.talents}`,
        '',
        '::: details 敌方开发详情',
        `- 预览：${line(enemy.preview, context)}`,
        '- 奖励档：F；终战不发奖励。',
        ':::',
        '',
      ]
    }),
  ].join('\n')
}

export function renderDocuments(input) {
  const report = input && typeof input.ok === 'boolean' && input.model ? input : validateLoadedContent(input)
  assertValidContent(report)
  const entities = report.model.entities
  const context = createContext(entities)
  const rules = entities.find((entity) => entity.id === 'RULES')
  const acts = entities.filter((entity) => entity.kind === 'act').sort((left, right) => ACT_IDS.indexOf(left.id) - ACT_IDS.indexOf(right.id))
  const methods = entities.filter((entity) => entity.kind === 'method').sort((left, right) => METHOD_IDS.indexOf(left.id) - METHOD_IDS.indexOf(right.id))
  const artifacts = entities.filter((entity) => entity.kind === 'artifact').sort((left, right) => ARTIFACT_IDS.indexOf(left.id) - ARTIFACT_IDS.indexOf(right.id))
  const events = entities.filter((entity) => entity.kind === 'event').sort((left, right) => left.id.localeCompare(right.id))
  const storylines = entities.filter((entity) => entity.kind === 'storyline').sort((left, right) => STORYLINE_IDS.indexOf(left.id) - STORYLINE_IDS.indexOf(right.id))
  const enemies = entities.filter((entity) => entity.kind === 'enemy').sort((left, right) => ENEMY_IDS.indexOf(left.id) - ENEMY_IDS.indexOf(right.id))
  const pages = new Map()
  pages.set('INDEX.md', renderIndex(report))
  pages.set('RULES.md', renderRules(rules))
  pages.set('ACTS.md', renderActs(acts, context))
  for (const method of methods) pages.set(`methods/${method.id}.md`, renderMethod(method, context))
  pages.set('artifacts/COMMON.md', renderArtifacts(artifacts, 'common', context))
  pages.set('artifacts/RARE.md', renderArtifacts(artifacts, 'rare', context))
  pages.set('artifacts/LEGENDARY.md', renderArtifacts(artifacts, 'legendary', context))
  for (let act = 1; act <= 4; act += 1) pages.set(`events/ACT${act}.md`, renderEvents(events, act, context))
  for (const storyline of storylines) pages.set(`storylines/${storyline.id}.md`, renderStoryline(storyline, events, context))
  pages.set('storylines/INDEPENDENT.md', renderIndependent(events.filter((event) => event.event_type === 'core'), storylines, context))
  for (let act = 1; act <= 4; act += 1) pages.set(`enemies/ACT${act}.md`, renderEnemies(enemies, act, context))
  pages.set('enemies/FINAL.md', renderFinalEnemies(enemies, context))

  const missing = DOCUMENT_PATHS.filter((documentPath) => !pages.has(documentPath))
  if (missing.length > 0 || pages.size !== DOCUMENT_PATHS.length) {
    throw new Error(`renderer did not produce the fixed 32-page set: missing ${missing.join(', ')}`)
  }
  for (const [documentPath, text] of pages.entries()) {
    if (!text.startsWith(GENERATED_HEADER)) throw new Error(`generated header missing from ${documentPath}`)
    if (!text.endsWith('\n')) pages.set(documentPath, `${text}\n`)
  }
  return pages
}

export const renderContentPages = renderDocuments

function assertFixedPages(pages) {
  if (!(pages instanceof Map)) throw new Error('generated documents must be a Map')
  if (pages.size !== DOCUMENT_PATHS.length || DOCUMENT_PATHS.some((documentPath) => !pages.has(documentPath))) {
    throw new Error('generated documents do not match the fixed 32-page document set')
  }
  for (const relativePath of pages.keys()) {
    if (!DOCUMENT_PATH_SET.has(relativePath)) throw new Error(`unknown generated document path ${relativePath}`)
    if (typeof pages.get(relativePath) !== 'string') throw new Error(`generated document is not text: ${relativePath}`)
  }
}

async function assertNoSymlinkPath(target) {
  let current = path.resolve(target)
  while (true) {
    try {
      const stat = await lstat(current)
      if (stat.isSymbolicLink()) throw new Error(`symlink output path is not allowed: ${current}`)
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error
    }
    const parent = path.dirname(current)
    if (parent === current) break
    current = parent
  }
}

function safeGeneratedPath(root, relativePath) {
  if (typeof relativePath !== 'string' || path.posix.normalize(relativePath) !== relativePath || path.posix.isAbsolute(relativePath)) {
    throw new Error(`unsafe generated document path ${relativePath}`)
  }
  const absolutePath = path.resolve(root, relativePath)
  const relative = path.relative(root, absolutePath)
  if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error(`unsafe generated document path ${relativePath}`)
  }
  return absolutePath
}

async function assertOutputRoot(root, { create = false } = {}) {
  await assertNoSymlinkPath(root)
  try {
    const stat = await lstat(root)
    if (!stat.isDirectory()) throw new Error(`output root is not a directory: ${root}`)
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error
    if (!create) throw new Error(`output root does not exist: ${root}`)
    await mkdir(root, { recursive: true })
    await assertNoSymlinkPath(root)
  }
}

async function readOutputFile(absolutePath, relativePath) {
  await assertNoSymlinkPath(absolutePath)
  let stat
  try {
    stat = await lstat(absolutePath)
  } catch (error) {
    if (error?.code === 'ENOENT') throw new Error(`missing generated document ${relativePath}`)
    throw error
  }
  if (stat.isSymbolicLink()) throw new Error(`symlink generated document is not allowed: ${relativePath}`)
  if (!stat.isFile()) throw new Error(`generated document is not a regular file: ${relativePath}`)
  return readFile(absolutePath, 'utf8')
}

export async function writeDocuments(pages, { outputRoot = DOCS_ROOT } = {}) {
  assertFixedPages(pages)
  const root = path.resolve(outputRoot)
  await assertOutputRoot(root, { create: true })
  let index = 0
  for (const [relativePath, text] of pages.entries()) {
    const absolutePath = safeGeneratedPath(root, relativePath)
    const parent = path.dirname(absolutePath)
    await assertNoSymlinkPath(parent)
    await mkdir(parent, { recursive: true })
    await assertNoSymlinkPath(parent)
    try {
      const stat = await lstat(absolutePath)
      if (stat.isSymbolicLink()) throw new Error(`symlink generated document is not allowed: ${relativePath}`)
      if (!stat.isFile()) throw new Error(`generated document target is not a regular file: ${relativePath}`)
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error
    }
    const temporary = path.join(parent, `.${path.basename(absolutePath)}.tmp-${process.pid}-${Date.now()}-${index}`)
    index += 1
    await writeFile(temporary, text, { encoding: 'utf8', flag: 'wx' })
    try {
      await assertNoSymlinkPath(temporary)
      await rename(temporary, absolutePath)
    } catch (error) {
      try {
        await unlink(temporary)
      } catch {
        // Preserve the original error; a failed cleanup must not hide it.
      }
      throw error
    }
  }
  return { outputRoot: root, paths: [...pages.keys()] }
}

export async function checkDocuments(pages, { outputRoot = DOCS_ROOT } = {}) {
  assertFixedPages(pages)
  const root = path.resolve(outputRoot)
  await assertOutputRoot(root)
  for (const relativePath of DOCUMENT_PATHS) {
    const absolutePath = safeGeneratedPath(root, relativePath)
    const actual = await readOutputFile(absolutePath, relativePath)
    const expected = pages.get(relativePath)
    if (actual !== expected) throw new Error(`generated document drift: ${relativePath}`)
  }
  return { outputRoot: root, paths: [...DOCUMENT_PATHS] }
}
