from pathlib import Path
import re
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else '.')
engine_path = root / 'src/engine.ts'
app_path = root / 'src/app.ts'
css_path = root / 'src/style.css'
gen_path = root / 'scripts/create-content.py'
test_path = root / 'tests/engine.test.mjs'
policy_path = root / 'tests/policy.mjs'
doc_path = root / 'docs/GAMEPLAY_V3.md'

ENGINE = r'''/** Pure deterministic rules. No DOM, clock, storage, or content IDs outside the supplied pack. */
export type Stat = 'hp'|'attack'|'defense'|'speed'|'hit'|'dodge'|'luck';
export type Slot = 'basic'|'rage'|'aux'|'artifact'|'strategy';
export type Stats = Record<Stat,number>;
export type Num = number | number[];
export interface Condition { type:string; target?:string; value?:number; key?:string; status?:string; tag?:string; stat?:Stat; text?:string; }
export interface Effect { type:string; target?:string; value?:any; coefficient?:Num; stat?:Stat; maxHpPercent?:number; percent?:Num; status?:string; pure?:boolean; key?:string; }
export interface Trigger { on:string; effects:Effect[]; once?:boolean; chance?:number; conditions?:Condition[]; }
export interface Ability { id:string; name:string; slot:Slot; tags:string[]; art:string; description:string; effects:Effect[]; triggers:Trigger[]; stats:Partial<Record<Stat,Num>>; rarity:string; cost:number; cooldown?:number; priority?:number; }
export interface Origin { id:string; name:string; subtitle:string; description:string; art:string; stats:Stats; affinity:string; starting:string[]; }
export interface Fate { id:string; name:string; art:string; description:string; stats?:Partial<Stats>; percent?:Partial<Stats>; triggers?:Trigger[]; damageByRound?:number[]; }
export interface BattleObjective { type:'kill'|'survive'|'break'; rounds?:number; value?:number; label?:string; }
export interface BossPhase { hpPercent:number; label:string; effects?:Effect[]; }
export interface Enemy { id:string; name:string; act:number; kind:string; art:string; stats:Stats; abilities:string[]; tags:string[]; intent:string; ai?:'greedy'|'weighted'; objective?:BattleObjective; phases?:BossPhase[]; }
export interface EventBranch { text:string; effects:Effect[]; grant?:{id?:string;slot?:Slot}|null; next?:string; }
export interface EventCheck { stat:Stat; base:number; difficulty:number; success:EventBranch; failure:EventBranch; }
export interface Choice { id:string; label:string; text:string; preview?:string; effects:Effect[]; grant?:{id?:string;slot?:Slot}|null; conditions:Condition[]; next?:string; check?:EventCheck; }
export interface EventPhase { id:string; text:string; choices:Choice[]; }
export interface Story {id:string;act:number;major:boolean;name:string;npc:string;art:string;text:string;choices:Choice[];phases?:EventPhase[];startPhase?:string;profile?:'A'|'B';weight?:number;maxPerRun?:number;}
export interface Ending { id:string; name:string; art:string; description:string; conditions:Condition[]; }
export interface Content { version:string;rulesVersion:string;title:string;subtitle:string;abilities:Ability[];origins:Origin[];fates:Fate[];enemies:Enemy[];events:Story[];acts:{name:string;subtitle:string;chapter:string;boss:string;major:string;tint:string}[];endings:Ending[];realms:string[];rules:{xpThresholds:number[];levelStats:Partial<Stats>;rageMax:number;basicRage:number;hitRage:number;maxRounds:number;burnDamage:number;weakPercent:number;breakDefense:number;vulnerablePercent:number;startingGold:number;refreshPrices:number[];restPercent:number;rewards:Record<string,{gold:number;xp:number}>};labels:Record<string,Record<string,string>>; }
export interface Equipped { id:string; rank:number; }
export interface RouteNode {id:string;act:number;row:number;lane:number;type:string;ref?:string;}
export type Phase = 'map'|'battle'|'reward'|'shop'|'rest'|'event'|'event_result'|'ending'|'finished'|'dead';
export interface Fighter {name:string;stats:Stats;hp:number;rage:number;shield:number;status:Record<string,number>;abilities:Equipped[];fate?:Fate;used:string[];tags:string[];cooldown:Record<string,number>;phase:number;}
export interface CombatBreakdown { base:number; scaled:number; afterDefense:number; afterVulnerable:number; afterCrit:number; absorbed:number; hpLoss:number; }
export interface Frame {round:number;actor:'p'|'e'|'system';kind:string;label:string;amount:number;crit?:boolean;p:Fighter;e:Fighter;sourceId?:string;detail?:string;breakdown?:CombatBreakdown;objective?:string;phase?:number;}
export interface BattleSummary {playerDamage:number;enemyDamage:number;playerShieldAbsorbed:number;enemyShieldAbsorbed:number;playerCrits:number;enemyCrits:number;playerMisses:number;enemyMisses:number;playerRageSkills:number;enemyRageSkills:number;statusTicks:number;phaseChanges:number;}
export interface Battle {enemyId:string;frames:Frame[];won:boolean;rounds:number;hp:number;cursor:number;objective:BattleObjective;summary:BattleSummary;objectiveProgress:number;}
export interface Stock {kind:'ability'|'heal'|'stat';id?:string;price:number;sold:boolean;stat?:Stat;value?:number;}
export interface Pending {id:string;source:'reward'|'shop'|'event';price:number;index?:number;}
export interface EventCheckResult {eventId:string;phase:string;choiceId:string;stat:Stat;chance:number;roll:number;success:boolean;}
export interface StoryLogItem {act:number;title:string;choice:string;phase?:string;result?:string;chance?:number;roll?:number;success?:boolean;}
export interface RunState {version:string;rulesVersion:string;seed:string;name:string;portrait:string;origin:string;fate:string;act:number;row:number;lane:number;phase:Phase;hp:number;gold:number;xp:number;level:number;bonus:Partial<Stats>;slots:(Equipped|null)[];rng:Record<string,number>;route:RouteNode[];visited:string[];facts:Record<string,boolean>;counters:Record<string,number>;threads:Record<string,string>;seenEvents:Record<string,number>;refreshes:number[];reward:string[];stock:Stock[];temper:Stat[];current?:RouteNode;battle?:Battle;pending?:Pending;eventId?:string;eventPhase?:string;eventStep?:number;lastCheck?:EventCheckResult;resultText?:string;endingId?:string;actionLog:{command:string;args:any[]}[];storyLog:StoryLogItem[];rewardInfo?:{gold:number;xp:number};}

export const SLOT_ORDER:Slot[]=['basic','rage','aux','aux','artifact','artifact','artifact','strategy'];
export const STAT_KEYS:Stat[]=['hp','attack','defense','speed','hit','dodge','luck'];
export const EFFECT_TYPES=['damage','heal','gain_shield','gain_rage','lose_rage','apply_status','remove_status','modify_stat','gain_currency','gain_xp','rank_up','set_fact','add_counter','advance_thread'];
export const TRIGGER_TYPES=['battle_start','before_action','after_action','on_hit','on_damaged','on_rage_skill','hp_threshold','round_end','battle_end'];
export const CONDITION_TYPES=['hp_below','hp_above','has_status','status_stack_at_least','rage_at_least','has_fact','counter_at_least','act_is','enemy_tag','player_tag','currency_at_least','hp_above_absolute','thread_is','event_seen','stat_at_least'];
export const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
export const value=(x:Num|undefined,r=0):number=>Math.trunc(Array.isArray(x)?x[Math.min(r,x.length-1)]:(x??0));
export const clamp=(x:number,min:number,max:number)=>Math.max(min,Math.min(max,x));
export function hash(text:string):number {let x=2166136261;for(let i=0;i<text.length;i++){x^=text.charCodeAt(i);x=Math.imul(x,16777619);}return (x>>>0)||1;}
export function random(s:{seed:string;rng:Record<string,number>},stream:string):number {let x=s.rng[stream]??hash(s.seed+'|'+stream);x^=x<<13;x^=x>>>17;x^=x<<5;s.rng[stream]=x>>>0;return (x>>>0)/4294967296;}
export function pick<T>(s:{seed:string;rng:Record<string,number>},stream:string,a:T[]):T {if(!a.length)throw new Error('Empty choice pool');return a[Math.floor(random(s,stream)*a.length)];}
export function sample<T>(s:{seed:string;rng:Record<string,number>},stream:string,a:T[],n:number):T[]{const pool=[...a],out:T[]=[];while(pool.length&&out.length<n)out.push(pool.splice(Math.floor(random(s,stream)*pool.length),1)[0]);return out;}
export function fateOptions(c:Content,seed:string):Fate[]{return sample({seed,rng:{}},'fate',c.fates,3);}

function weighted<T>(s:{seed:string;rng:Record<string,number>},stream:string,items:T[],weight:(x:T)=>number):T {
 if(!items.length)throw new Error('Empty weighted pool');const weights=items.map(x=>Math.max(0,weight(x))),total=weights.reduce((a,b)=>a+b,0);if(total<=0)return items[0];
 let cursor=random(s,stream)*total;for(let i=0;i<items.length;i++){if(cursor<weights[i])return items[i];cursor-=weights[i];}return items[items.length-1];
}

export function validateContent(c:Content):void {
 if(!c||!c.version||!Array.isArray(c.abilities))throw new Error('Invalid content pack');
 const ids=new Set<string>();for(const list of [c.abilities,c.origins,c.fates,c.enemies,c.events,c.endings])for(const entity of list){if(!entity.id||ids.has(entity.id))throw new Error('Duplicate or missing ID: '+entity.id);ids.add(entity.id);}
 const abilities=new Set(c.abilities.map(x=>x.id));
 const checkConditions=(a:Condition[])=>{for(const x of a){if(!CONDITION_TYPES.includes(x.type))throw new Error('Unknown condition '+x.type);if(x.stat&&!STAT_KEYS.includes(x.stat))throw new Error('Unknown condition stat');}};
 const checkEffects=(a:Effect[])=>{for(const e of a){if(!EFFECT_TYPES.includes(e.type))throw new Error('Unknown effect '+e.type);if(e.coefficient!==undefined&&[e.coefficient].flat().some(x=>!Number.isFinite(x)||x<0||x>2000))throw new Error('Unsafe coefficient');if(e.stat&&!STAT_KEYS.includes(e.stat))throw new Error('Unknown stat');}};
 const checkGrant=(g:{id?:string;slot?:Slot}|null|undefined)=>{if(g?.id&&!abilities.has(g.id))throw new Error('Broken grant');if(g?.slot&&!SLOT_ORDER.includes(g.slot))throw new Error('Broken grant slot');};
 const checkChoice=(choice:Choice,phaseIds?:Set<string>)=>{checkEffects(choice.effects??[]);checkConditions(choice.conditions??[]);checkGrant(choice.grant);if(choice.next&&phaseIds&&!phaseIds.has(choice.next))throw new Error('Broken event phase '+choice.next);if(choice.check){if(!STAT_KEYS.includes(choice.check.stat)||!Number.isFinite(choice.check.base)||!Number.isFinite(choice.check.difficulty))throw new Error('Invalid event check');for(const branch of [choice.check.success,choice.check.failure]){checkEffects(branch.effects??[]);checkGrant(branch.grant);if(branch.next&&phaseIds&&!phaseIds.has(branch.next))throw new Error('Broken event branch '+branch.next);}}};
 for(const a of c.abilities){if(!SLOT_ORDER.includes(a.slot))throw new Error('Invalid slot');if((a.cooldown??0)<0||(a.cooldown??0)>20)throw new Error('Invalid cooldown');checkEffects(a.effects);for(const t of a.triggers){if(!TRIGGER_TYPES.includes(t.on))throw new Error('Unknown trigger');checkEffects(t.effects);checkConditions(t.conditions??[]);}}
 for(const f of c.fates)for(const t of f.triggers??[]){checkEffects(t.effects);checkConditions(t.conditions??[]);}
 for(const x of [...c.origins.map(x=>({ids:x.starting,stats:x.stats})),...c.enemies.map(x=>({ids:x.abilities,stats:x.stats}))]){for(const id of x.ids)if(!abilities.has(id))throw new Error('Broken ability reference '+id);for(const key of STAT_KEYS)if(!Number.isInteger(x.stats[key])||x.stats[key]<0||x.stats[key]>10000)throw new Error('Invalid stat '+key);if(x.stats.hp<1)throw new Error('Invalid HP');}
 for(const enemy of c.enemies){if(enemy.objective&&!['kill','survive','break'].includes(enemy.objective.type))throw new Error('Invalid objective');for(const p of enemy.phases??[]){if(p.hpPercent<=0||p.hpPercent>=100)throw new Error('Invalid boss phase');checkEffects(p.effects??[]);}}
 for(const e of c.events){if((e.phases?.length??0)>5)throw new Error('Too many event phases');const phaseIds=new Set((e.phases??[]).map(p=>p.id));if(e.phases?.length&&phaseIds.size!==e.phases.length)throw new Error('Duplicate event phase');if(e.startPhase&& !phaseIds.has(e.startPhase))throw new Error('Broken start phase');for(const choice of e.choices??[])checkChoice(choice,phaseIds);for(const p of e.phases??[]){if(p.choices.length<2||p.choices.length>4)throw new Error('Event phase must have 2-4 choices');for(const choice of p.choices)checkChoice(choice,phaseIds);}}
 for(const a of c.acts){if(!c.enemies.some(e=>e.id===a.boss)||!c.events.some(e=>e.id===a.major))throw new Error('Broken act reference');}
 for(const e of c.endings)checkConditions(e.conditions);
}

export function playerStats(c:Content,s:RunState):Stats {
 const o=c.origins.find(x=>x.id===s.origin)!;const f=c.fates.find(x=>x.id===s.fate)!;const r={...o.stats};
 for(const k of STAT_KEYS)r[k]+=value(s.bonus[k])+value(f.stats?.[k])+value(c.rules.levelStats[k])*s.level;
 for(const eq of s.slots)if(eq){const a=c.abilities.find(x=>x.id===eq.id)!;for(const k of STAT_KEYS)r[k]+=value(a.stats[k],eq.rank);}
 for(const k of STAT_KEYS)r[k]=Math.max(k==='hp'?1:0,Math.floor(r[k]*(100+value(f.percent?.[k]))/100));return r;
}
function fighter(c:Content,s:RunState,enemy?:Enemy):Fighter {const stats=enemy?{...enemy.stats}:playerStats(c,s);return {name:enemy?.name??s.name,stats,hp:enemy?stats.hp:Math.min(s.hp,stats.hp),rage:0,shield:0,status:{},abilities:enemy?enemy.abilities.map(id=>({id,rank:0})):clone(s.slots.filter((x):x is Equipped=>!!x)),fate:enemy?undefined:c.fates.find(x=>x.id===s.fate),used:[],tags:enemy?.tags??[c.origins.find(x=>x.id===s.origin)!.affinity],cooldown:{},phase:0};}

export function conditionOK(c:Content,s:RunState,q:Condition,self?:Fighter,enemy?:Fighter):boolean {
 const who=q.target==='enemy'?enemy:self;const hp=who?.hp??s.hp,max=who?.stats.hp??playerStats(c,s).hp;const n=q.status==='shield'?(who?.shield??0):(who?.status[q.status??'']??0);
 switch(q.type){case 'hp_below':return hp*100<max*(q.value??0);case 'hp_above':return hp*100>max*(q.value??0);case 'hp_above_absolute':return hp>(q.value??0);case 'has_status':return n>0;case 'status_stack_at_least':return n>=(q.value??1);case 'rage_at_least':return (who?.rage??0)>=(q.value??0);case 'has_fact':return !!s.facts[q.key??''];case 'counter_at_least':return (s.counters[q.key??'']??0)>=(q.value??0);case 'currency_at_least':return s.gold>=(q.value??0);case 'act_is':return s.act===(q.value??0);case 'enemy_tag':return !!enemy?.tags.includes(q.tag??'');case 'player_tag':return !!self?.tags.includes(q.tag??'');case 'thread_is':return s.threads[q.key??'']===q.text;case 'event_seen':return (s.seenEvents[q.key??'']??0)>=(q.value??1);case 'stat_at_least':return playerStats(c,s)[q.stat??'luck']>=(q.value??0);default:throw new Error('Unsupported condition: '+q.type);}
}

/** Resolve once, then replay snapshots. Playback speed can never alter the result. */
export function simulateBattle(c:Content,s:RunState,enemy:Enemy):Battle {
 const p=fighter(c,s),e=fighter(c,s,enemy),frames:Frame[]=[];let round=0,eventBudget=0,objectiveProgress=0,objectiveWon=false;
 const objective:BattleObjective=clone(enemy.objective??{type:'kill',label:'击败敌人'});const summary:BattleSummary={playerDamage:0,enemyDamage:0,playerShieldAbsorbed:0,enemyShieldAbsorbed:0,playerCrits:0,enemyCrits:0,playerMisses:0,enemyMisses:0,playerRageSkills:0,enemyRageSkills:0,statusTicks:0,phaseChanges:0};
 const side=(f:Fighter)=>f===p?'p':f===e?'e':'system';
 const frame=(actor:Fighter|undefined,kind:string,label:string,amount=0,crit=false,meta:Partial<Frame>={})=>frames.push({round,actor:actor?side(actor):'system',kind,label,amount,crit,p:clone(p),e:clone(e),...meta});
 const stat=(f:Fighter,k:Stat)=>k==='attack'?Math.max(1,Math.floor(f.stats.attack*(f.status.weak?100-c.rules.weakPercent:100)/100)):k==='defense'?Math.max(0,f.stats.defense-(f.status.break??0)*c.rules.breakDefense):f.stats[k];
 const changeRage=(f:Fighter,n:number)=>{f.rage=clamp(f.rage+n,0,c.rules.rageMax);};
 const stream=(f:Fighter,kind:string)=>`combat.${f===p?'p':'e'}.${kind}`;
 function hurt(a:Fighter,b:Fighter,n:number,label:string,crit=false,breakdown?:CombatBreakdown,sourceId?:string){n=Math.max(1,Math.floor(n));const absorbed=Math.min(b.shield,n);b.shield-=absorbed;const hpLoss=Math.max(0,n-absorbed);b.hp=Math.max(0,b.hp-hpLoss);if(b===p){summary.enemyDamage+=hpLoss;summary.playerShieldAbsorbed+=absorbed;}else{summary.playerDamage+=hpLoss;summary.enemyShieldAbsorbed+=absorbed;if(a===p)objectiveProgress+=hpLoss+absorbed;}if(breakdown){breakdown.absorbed=absorbed;breakdown.hpLoss=hpLoss;}frame(a,'damage',label,hpLoss,crit,{sourceId,breakdown,detail:absorbed?`护盾吸收 ${absorbed}`:undefined});if(objective.type==='break'&&objectiveProgress>=(objective.value??1))objectiveWon=true;if(b===e)checkBossPhase();}
 function apply(a:Fighter,b:Fighter,ef:Effect,rank:number,label:string,secondary=false,sourceId?:string){if(++eventBudget>768)throw new Error('Combat effect budget exceeded');const t=ef.target==='self'?a:b;const n=value(ef.value,rank);switch(ef.type){case 'damage':{let base=n;let scaled=base+Math.floor(stat(a,ef.stat??'attack')*value(ef.coefficient,rank)/100)+Math.floor(t.stats.hp*(ef.maxHpPercent??0)/100);let afterDefense=ef.pure?Math.max(1,scaled):Math.max(1,scaled-stat(t,'defense'));let afterVulnerable=t.status.vulnerable?Math.floor(afterDefense*(100+c.rules.vulnerablePercent)/100):afterDefense;let crit=false;if(t!==a&&!secondary){const hit=clamp(9500+a.stats.hit*50-t.stats.dodge*50,6000,10000);if(random(s,stream(a,'hit'))*10000>=hit){if(a===p)summary.playerMisses++;else summary.enemyMisses++;frame(a,'miss',label,0,false,{sourceId,detail:`命中率 ${(hit/100).toFixed(1)}%`});return false;}crit=random(s,stream(a,'crit'))*10000<Math.min(4000,500+a.stats.luck*30);if(crit){afterVulnerable=Math.floor(afterVulnerable*150/100);if(a===p)summary.playerCrits++;else summary.enemyCrits++;}}let afterCrit=afterVulnerable;if(a.fate?.damageByRound&&t!==a)afterCrit=Math.floor(afterCrit*a.fate.damageByRound[Math.min(Math.max(round-1,0),a.fate.damageByRound.length-1)]/100);const breakdown:CombatBreakdown={base,scaled,afterDefense,afterVulnerable,afterCrit,absorbed:0,hpLoss:0};hurt(a,t,afterCrit,label,crit,breakdown,sourceId);return true;}case 'heal':t.hp=Math.min(t.stats.hp,t.hp+n+Math.floor(t.stats.hp*(ef.maxHpPercent??0)/100));break;case 'gain_shield':t.shield=Math.min(9999,t.shield+n+Math.floor(stat(a,ef.stat??'defense')*value(ef.coefficient,rank)/100));break;case 'gain_rage':changeRage(t,n);break;case 'lose_rage':changeRage(t,-n);break;case 'apply_status':t.status[ef.status!]=clamp((t.status[ef.status!]??0)+n,0,ef.status==='stun'?1:20);break;case 'remove_status':delete t.status[ef.status!];break;case 'modify_stat':{const k=ef.stat!;t.stats[k]=Math.max(k==='hp'?1:0,Math.floor(t.stats[k]*(100+value(ef.percent,rank))/100)+n);if(k==='hp')t.hp=Math.min(t.hp,t.stats.hp);break;}default:throw new Error('Non-combat effect in combat: '+ef.type);}return true;}
 function checkBossPhase(){const phases=enemy.phases??[];while(e.phase<phases.length&&e.hp*100<=e.stats.hp*phases[e.phase].hpPercent){const ph=phases[e.phase++];summary.phaseChanges++;frame(undefined,'phase',ph.label,0,false,{phase:e.phase,detail:`生命降至 ${ph.hpPercent}% 阈值`});for(const ef of ph.effects??[])apply(e,p,ef,0,ph.label,true,'boss.phase');}}
 function trigger(a:Fighter,b:Fighter,on:string){if(a.hp<=0)return;const list=[...a.abilities.map(eq=>({id:eq.id,rank:eq.rank,triggers:c.abilities.find(x=>x.id===eq.id)!.triggers})),...(a.fate?[{id:'fate',rank:0,triggers:a.fate.triggers??[]}]:[])];for(const item of list)for(let i=0;i<item.triggers.length;i++){const t=item.triggers[i],key=item.id+':'+i;if(t.on!==on||(t.once&&a.used.includes(key))||!(t.conditions??[]).every(q=>conditionOK(c,s,q,a,b)))continue;if(t.chance!==undefined&&random(s,stream(a,'trigger.'+on))*100>=t.chance)continue;if(t.once)a.used.push(key);for(const effect of t.effects){if(b.hp<=0&&effect.target!=='self')continue;apply(a,b,effect,item.rank,c.abilities.find(x=>x.id===item.id)?.name??a.fate?.name??on,true,item.id);}}}
 function legalActions(a:Fighter){return a.abilities.map(eq=>({eq,ability:c.abilities.find(x=>x.id===eq.id)!})).filter(x=>['basic','rage'].includes(x.ability.slot)&&(a.cooldown[x.ability.id]??0)<=0&&(x.ability.slot!=='rage'||a.rage>=x.ability.cost));}
 function actionScore(x:{eq:Equipped;ability:Ability}){const hit=x.ability.effects.find(e=>e.type==='damage');return (x.ability.priority??0)+(x.ability.slot==='rage'?200:0)+value(hit?.coefficient,x.eq.rank)+value(hit?.value,x.eq.rank);}
 function chooseAction(a:Fighter){const all=legalActions(a);if(!all.length)return undefined;if(a===p){const rage=all.filter(x=>x.ability.slot==='rage').sort((x,y)=>actionScore(y)-actionScore(x));if(rage.length)return rage[0];return all.filter(x=>x.ability.slot==='basic').sort((x,y)=>actionScore(y)-actionScore(x))[0]??all[0];}if(enemy.ai==='weighted')return weighted(s,'combat.enemy_ai',all,x=>Math.max(1,actionScore(x)));return [...all].sort((x,y)=>actionScore(y)-actionScore(x)||x.ability.id.localeCompare(y.ability.id))[0];}
 function tickStatuses(a:Fighter,b:Fighter){let changed=false;if(a.status.burn&&a.hp>0){const n=a.status.burn*c.rules.burnDamage;a.status.burn=Math.max(0,a.status.burn-1);summary.statusTicks++;hurt(b,a,n,'燃烧',false,{base:n,scaled:n,afterDefense:n,afterVulnerable:n,afterCrit:n,absorbed:0,hpLoss:0},'status.burn');changed=true;}for(const st of ['weak','break','vulnerable'])if(a.status[st]){a.status[st]=Math.max(0,a.status[st]-1);changed=true;}if(changed&&a.hp>0)frame(undefined,'status_tick',a.name+' 状态结算',0,false,{detail:'持续状态衰减'});}
 function objectiveReached(){if(p.hp<=0)return false;if(objective.type==='kill')return e.hp<=0;if(objective.type==='break')return objectiveWon;if(objective.type==='survive')return round>=(objective.rounds??1);return false;}
 frame(undefined,'start','斗法开始',0,false,{objective:objective.label??objective.type});trigger(p,e,'battle_start');trigger(e,p,'battle_start');frame(undefined,'ready','命格与法宝已生效');
 for(round=1;round<=c.rules.maxRounds&&p.hp>0&&e.hp>0&&!objectiveWon;round++){
  eventBudget=0;for(const a of [p,e])for(const id of Object.keys(a.cooldown))if(a.cooldown[id]>0)a.cooldown[id]--;
  const order=p.stats.speed>=e.stats.speed?[p,e]:[e,p];
  for(const a of order){const b=a===p?e:p;if(a.hp<=0||b.hp<=0||objectiveWon)break;if(a.status.stun){delete a.status.stun;frame(a,'stun','眩晕，跳过行动');continue;}trigger(a,b,'before_action');trigger(a,b,'hp_threshold');if(a.hp<=0||b.hp<=0)break;const picked=chooseAction(a);if(!picked){changeRage(a,5);frame(a,'wait','无可用主行动',0,false,{detail:'冷却或怒气条件未满足；怒气 +5'});continue;}const {eq,ability}=picked,useRage=ability.slot==='rage';if(useRage){changeRage(a,-ability.cost);if(a===p)summary.playerRageSkills++;else summary.enemyRageSkills++;}let hit=false;for(const ef of ability.effects){if(b.hp<=0&&ef.target!=='self')continue;const landed=apply(a,b,ef,eq.rank,ability.name,false,ability.id);if(ef.type==='damage'&&ef.target!=='self')hit=landed!==false;if(objectiveWon)break;}if(ability.cooldown)a.cooldown[ability.id]=ability.cooldown;if(ability.slot==='basic')changeRage(a,c.rules.basicRage);if(hit){changeRage(b,c.rules.hitRage);trigger(a,b,'on_hit');trigger(b,a,'on_damaged');trigger(b,a,'hp_threshold');}if(useRage)trigger(a,b,'on_rage_skill');trigger(a,b,'after_action');trigger(a,b,'hp_threshold');frame(a,useRage?'rage':'action',ability.name,0,false,{sourceId:ability.id,detail:ability.cooldown?`进入 ${ability.cooldown} 回合冷却`:undefined});if(objectiveReached()){objectiveWon=true;break;}}
  if(p.hp<=0||e.hp<=0||objectiveWon)break;for(const a of [p,e]){const b=a===p?e:p;trigger(a,b,'round_end');tickStatuses(a,b);trigger(a,b,'hp_threshold');if(p.hp<=0||e.hp<=0)break;}if(objectiveReached()){objectiveWon=true;break;}
 }
 const won=p.hp>0&&(objectiveWon||(objective.type==='kill'&&e.hp<=0));if(won)trigger(p,e,'battle_end');if(!won&&p.hp>0){p.hp=0;frame(undefined,'timeout','劫气耗尽',0,false,{detail:'未在规则允许的回合内完成目标'});}frame(undefined,won?'win':'loss',won?'斗法告捷':'此身入劫',0,false,{objective:objective.label??objective.type,detail:won?`目标完成：${objective.label??objective.type}`:`目标失败：${objective.label??objective.type}`});
 return {enemyId:enemy.id,frames,won,rounds:Math.min(round,c.rules.maxRounds),hp:p.hp,cursor:0,objective,summary,objectiveProgress};
}

export class Game {
 c:Content;s:RunState;
 constructor(c:Content,s:RunState){this.c=c;this.s=s;}
 static create(c:Content,seed:string,origin:string,fate:string,name='无名',portrait=''):Game {
  validateContent(c);const o=c.origins.find(x=>x.id===origin);if(!o||!fateOptions(c,seed).some(x=>x.id===fate))throw new Error('Invalid origin or offered fate');
  const s:RunState={version:c.version,rulesVersion:c.rulesVersion,seed,name:name.slice(0,14)||'无名',portrait:portrait||o.art,origin,fate,act:0,row:0,lane:1,phase:'map',hp:0,gold:c.rules.startingGold,xp:0,level:0,bonus:{},slots:SLOT_ORDER.map(()=>null),rng:{},route:[],visited:[],facts:{},counters:{mercy:0,defiance:0,chan_relation:0,jie_relation:0},threads:{},seenEvents:{},refreshes:[0,0,0,0],reward:[],stock:[],temper:[],actionLog:[],storyLog:[]};
  for(const id of o.starting){const a=c.abilities.find(x=>x.id===id)!;const index=SLOT_ORDER.findIndex((slot,i)=>slot===a.slot&&!s.slots[i]);s.slots[index]={id,rank:0};}s.hp=playerStats(c,s).hp;
  const planned:Record<string,number>={};const chooseStory=(act:number,streamName:string)=>{let pool=c.events.filter(e=>e.act===act&&!e.major).filter(e=>(planned[e.id]??0)<(e.maxPerRun??(e.profile==='B'?2:1)));if(!pool.length)pool=c.events.filter(e=>e.act===act&&!e.major);const chosen=weighted(s,streamName,pool,e=>e.weight??1);planned[chosen.id]=(planned[chosen.id]??0)+1;return chosen.id;};
  for(let act=0;act<c.acts.length;act++){const hiddenThisAct=random(s,'route.hidden')<.7;for(let row=0;row<6;row++){const types=row===0?['combat','combat','combat']:row===1?['event','event','event']:row===2?(hiddenThisAct?['combat','hidden','shop']:['combat','rest','shop']):row===3?['rest','elite','shop']:row===4?['major']:['boss'];const order=row===2||row===3?sample(s,'route',types,3):types;order.forEach((type,i)=>{const lane=order.length===1?1:i;let ref:string|undefined;if(['combat','elite'].includes(type))ref=pick(s,'route.encounter',c.enemies.filter(e=>e.act===act&&e.kind===type)).id;if(type==='event'||type==='hidden')ref=chooseStory(act,type==='hidden'?'event.hidden':'event.route');if(type==='major')ref=c.acts[act].major;if(type==='boss')ref=c.acts[act].boss;s.route.push({id:`${act}.${row}.${lane}`,act,row,lane,type,ref});});}}
  return new Game(c,s);
 }
 static load(c:Content,text:string):Game {
  if(text.length>4000000)throw new Error('Save too large');const s=JSON.parse(text) as RunState;if(s.version!==c.version||s.rulesVersion!==c.rulesVersion)throw new Error('Save/content version mismatch');if(!c.origins.some(o=>o.id===s.origin)||!c.fates.some(f=>f.id===s.fate)||typeof s.seed!=='string'||typeof s.name!=='string')throw new Error('Invalid identity');if(!Array.isArray(s.slots)||s.slots.length!==8||!s.slots[0]||!s.slots[1])throw new Error('Invalid slots');const seen=new Set<string>();s.slots.forEach((eq,i)=>{if(eq){const a=c.abilities.find(x=>x.id===eq.id);if(!a||a.slot!==SLOT_ORDER[i]||!Number.isInteger(eq.rank)||eq.rank<0||eq.rank>3||seen.has(eq.id))throw new Error('Invalid ability');seen.add(eq.id);}});for(const k of ['hp','gold','xp','level','act','row','lane'] as const)if(!Number.isInteger(s[k])||s[k]<0)throw new Error('Invalid '+k);if(s.act>=c.acts.length||s.row>5||s.lane>2||s.level>=c.realms.length||!['map','battle','reward','shop','rest','event','event_result','ending','finished','dead'].includes(s.phase))throw new Error('Invalid progress');if(!s.rng||!s.facts||!s.counters||!s.threads||!s.seenEvents||!Array.isArray(s.route)||!Array.isArray(s.actionLog)||s.actionLog.length>10000)throw new Error('Invalid save shape');if(s.phase==='battle'&&(!s.battle||!c.enemies.some(e=>e.id===s.battle!.enemyId)||!Array.isArray(s.battle.frames)||s.battle.frames.length>4000))throw new Error('Invalid replay');if(s.pending&&!c.abilities.some(a=>a.id===s.pending!.id))throw new Error('Invalid pending reward');if(['event','event_result'].includes(s.phase)&&!c.events.some(e=>e.id===s.eventId))throw new Error('Invalid story');return new Game(c,s);
 }
 stats():Stats{return playerStats(this.c,this.s);}
 ability(id:string):Ability {const a=this.c.abilities.find(a=>a.id===id);if(!a)throw new Error('Unknown ability');return a;}
 log(command:string,...args:any[]){this.s.actionLog.push({command,args});}
 available():RouteNode[]{const s=this.s;return s.phase==='map'?s.route.filter(n=>n.act===s.act&&n.row===s.row&&(s.row===0||Math.abs(n.lane-s.lane)<=1)):[];}
 enter(id:string){const n=this.available().find(x=>x.id===id);if(!n)throw new Error('Node not reachable');const s=this.s;s.current=n;s.lane=n.lane;s.visited.push(n.id);s.pending=undefined;s.resultText=undefined;s.lastCheck=undefined;this.log('enter',id);if(['combat','elite','boss'].includes(n.type)){s.phase='battle';s.battle=simulateBattle(this.c,s,this.c.enemies.find(e=>e.id===n.ref)!);}else if(n.type==='event'||n.type==='major'||n.type==='hidden'){s.phase='event';s.eventId=n.ref;const ev=this.c.events.find(e=>e.id===n.ref)!;s.eventPhase=ev.startPhase??ev.phases?.[0]?.id;s.eventStep=0;s.seenEvents[ev.id]=(s.seenEvents[ev.id]??0)+1;}else if(n.type==='shop'){s.phase='shop';this.rollShop();}else{s.phase='rest';s.temper=sample(s,'reward',STAT_KEYS,3);}}
 advance(){const s=this.s;s.pending=undefined;s.battle=undefined;s.reward=[];s.stock=[];s.resultText=undefined;s.lastCheck=undefined;s.eventId=undefined;s.eventPhase=undefined;s.eventStep=undefined;if(s.row===5){if(s.act===this.c.acts.length-1){s.phase='ending';return;}s.act++;s.row=0;s.lane=1;}else{s.row++;}s.phase='map';s.current=undefined;}
 finishBattle(){const s=this.s;if(s.phase!=='battle'||!s.battle)throw new Error('No battle');this.log('finishBattle');s.hp=s.battle.hp;if(!s.battle.won){s.phase='dead';return;}const gain=this.c.rules.rewards[s.current!.type];s.gold+=gain.gold;this.gainXP(gain.xp);s.rewardInfo=clone(gain);s.phase='reward';s.reward=this.rollAbilities(3,'reward');}
 gainXP(amount:number){this.s.xp+=amount;while(this.s.level+1<this.c.rules.xpThresholds.length&&this.s.xp>=this.c.rules.xpThresholds[this.s.level+1])this.s.level++;}
 rollAbilities(n:number,streamName:string,slot?:Slot):string[]{const s=this.s,affinity=this.c.origins.find(o=>o.id===s.origin)!.affinity;let pool=this.c.abilities.filter(a=>a.rarity!=='mythic'&&(!slot||a.slot===slot)&&!s.slots.some(eq=>eq?.id===a.id&&eq.rank===3));const out:string[]=[];while(pool.length&&out.length<n){const a=weighted(s,streamName,pool,x=>x.tags.includes(affinity)?3:1);out.push(a.id);pool=pool.filter(x=>x.id!==a.id);}return out;}
 acquire(id:string,source:Pending['source'],price=0,index?:number){const s=this.s;if(s.pending)throw new Error('Resolve existing replacement');if(s.gold<price)throw new Error('Not enough currency');const a=this.ability(id),duplicate=s.slots.findIndex(eq=>eq?.id===id);if(duplicate>=0){if(s.slots[duplicate]!.rank>=3)throw new Error('Maximum rank');s.slots[duplicate]!.rank++;this.completeAcquire({id,source,price,index});return;}const empty=SLOT_ORDER.findIndex((slot,i)=>slot===a.slot&&!s.slots[i]);if(empty>=0){s.slots[empty]={id,rank:0};this.completeAcquire({id,source,price,index});return;}s.pending={id,source,price,index};}
 completeAcquire(pending:Pending){const s=this.s;s.gold-=pending.price;if(pending.source==='shop')s.stock[pending.index!].sold=true;s.hp=Math.min(s.hp,this.stats().hp);s.pending=undefined;if(pending.source==='reward')this.advance();}
 replace(index:number){const p=this.s.pending;if(!p||SLOT_ORDER[index]!==this.ability(p.id).slot||!this.s.slots[index])throw new Error('Invalid replacement');if(this.s.gold<p.price)throw new Error('Not enough currency');this.log('replace',index);this.s.slots[index]={id:p.id,rank:0};this.completeAcquire(p);}
 cancelReplacement(){if(!this.s.pending)throw new Error('No replacement');this.log('cancelReplacement');this.s.pending=undefined;}
 reward(index:number){if(this.s.phase!=='reward'||!this.s.reward[index]||this.s.pending)throw new Error('No reward');this.log('reward',index);this.acquire(this.s.reward[index],'reward');}
 skipReward(){if(this.s.phase!=='reward'||this.s.pending)throw new Error('No reward');this.log('skipReward');this.advance();}
 rollShop(){const s=this.s;s.stock=this.rollAbilities(3,'shop').map(id=>({kind:'ability' as const,id,price:this.ability(id).rarity==='rare'?55:35,sold:false}));s.stock.push({kind:'heal',price:25,value:30,sold:false});const stat=pick(s,'shop.stat',STAT_KEYS.filter(x=>x!=='hp'));s.stock.push({kind:'stat',price:45,stat,value:stat==='attack'?2:1,sold:false});}
 buy(index:number){const s=this.s,offer=s.stock[index];if(s.phase!=='shop'||s.pending||!offer||offer.sold||s.gold<offer.price)throw new Error('Cannot buy');this.log('buy',index);if(offer.kind==='ability')this.acquire(offer.id!,'shop',offer.price,index);else if(offer.kind==='heal'){s.gold-=offer.price;s.hp=Math.min(this.stats().hp,s.hp+Math.floor(this.stats().hp*(offer.value??30)/100));offer.sold=true;}else{s.gold-=offer.price;s.bonus[offer.stat!]=(s.bonus[offer.stat!]??0)+(offer.value??1);offer.sold=true;}}
 refresh(){const s=this.s,n=s.refreshes[s.act],price=this.c.rules.refreshPrices[n];if(s.phase!=='shop'||s.pending||price===undefined||s.gold<price)throw new Error('Cannot refresh');this.log('refresh');s.gold-=price;s.refreshes[s.act]++;this.rollShop();}
 leaveShop(){if(this.s.phase!=='shop'||this.s.pending)throw new Error('Not in shop');this.log('leaveShop');this.advance();}
 rest(kind:string,index?:number){const s=this.s;if(s.phase!=='rest')throw new Error('Not resting');if(kind==='heal')s.hp=Math.min(this.stats().hp,s.hp+Math.floor(this.stats().hp*this.c.rules.restPercent/100));else if(kind==='temper'){const stat=s.temper[index??-1];if(!stat)throw new Error('Invalid temper');s.bonus[stat]=(s.bonus[stat]??0)+(stat==='hp'?12:stat==='attack'?3:2);}else{const eq=s.slots[index??-1];if(!eq||eq.rank>=3||((this.ability(eq.id).slot==='artifact')!==(kind==='artifact')))throw new Error('Cannot rank up');eq.rank++;}this.log('rest',kind,index);this.advance();}
 applyWorld(ef:Effect){const s=this.s,n=value(ef.value);switch(ef.type){case 'heal':s.hp=Math.min(this.stats().hp,s.hp+n+Math.floor(this.stats().hp*(ef.maxHpPercent??0)/100));break;case 'damage':s.hp=Math.max(0,s.hp-n-Math.floor(this.stats().hp*(ef.maxHpPercent??0)/100));break;case 'gain_currency':s.gold=Math.max(0,s.gold+n);break;case 'gain_xp':this.gainXP(n);break;case 'modify_stat':s.bonus[ef.stat!]=(s.bonus[ef.stat!]??0)+n+Math.floor(this.stats()[ef.stat!]*value(ef.percent)/100);break;case 'set_fact':s.facts[ef.key!]=!!ef.value;break;case 'add_counter':s.counters[ef.key!]=(s.counters[ef.key!]??0)+n;break;case 'advance_thread':s.threads[ef.key!]=String(ef.value);break;case 'rank_up':{const eq=s.slots.find(x=>x?.id===ef.key);if(eq)eq.rank=Math.min(3,eq.rank+Math.max(1,n));break;}default:throw new Error('Non-world effect in event: '+ef.type);}}
 currentEvent():Story {const e=this.c.events.find(x=>x.id===this.s.eventId);if(!e)throw new Error('No event');return e;}
 eventPhase():EventPhase {const event=this.currentEvent();if(!event.phases?.length)return {id:'root',text:event.text,choices:event.choices};const id=this.s.eventPhase??event.startPhase??event.phases[0].id;const phase=event.phases.find(p=>p.id===id);if(!phase)throw new Error('Invalid event phase');return phase;}
 checkChance(choice:Choice):number|undefined {if(!choice.check)return undefined;const st=this.stats();return clamp(Math.round(choice.check.base+(st[choice.check.stat]-choice.check.difficulty)*4+st.luck/5),10,95);}
 eventChoices(){const event=this.currentEvent(),phase=this.eventPhase();return phase.choices.map(choice=>({choice,legal:(choice.conditions??[]).every(q=>conditionOK(this.c,this.s,q)),chance:this.checkChance(choice),stat:choice.check?.stat,eventId:event.id,phase:phase.id}));}
 chooseEvent(id:string){const s=this.s;if(s.phase!=='event'||s.pending)throw new Error('No event');const event=this.currentEvent(),phase=this.eventPhase(),info=this.eventChoices().find(x=>x.choice.id===id);if(!info||!info.legal)throw new Error('Choice locked');const choice=info.choice;this.log('chooseEvent',id);let result=choice.text,next=choice.next,grant=choice.grant,chance:number|undefined,roll:number|undefined,success:boolean|undefined;if(choice.check){chance=info.chance!;roll=Math.floor(random(s,`event.check.${event.id}.${phase.id}.${choice.id}`)*100)+1;success=roll<=chance;const branch=success?choice.check.success:choice.check.failure;for(const ef of branch.effects??[])this.applyWorld(ef);result=branch.text;next=branch.next;grant=branch.grant;s.lastCheck={eventId:event.id,phase:phase.id,choiceId:choice.id,stat:choice.check.stat,chance,roll,success};}else for(const ef of choice.effects??[])this.applyWorld(ef);s.storyLog.push({act:s.act,title:event.name,choice:choice.label,phase:phase.id,result,chance,roll,success});s.resultText=result;if(s.hp<=0){s.phase='dead';return;}if(next){if((s.eventStep??0)>=4)throw new Error('Event phase budget exceeded');s.eventPhase=next;s.eventStep=(s.eventStep??0)+1;s.phase='event';}else s.phase='event_result';if(grant){const ability=grant.id??this.rollAbilities(1,'event.reward',grant.slot)[0];if(ability)this.acquire(ability,'event');}}
 leaveEvent(){if(this.s.phase!=='event_result'||this.s.pending)throw new Error('Unresolved event');this.log('leaveEvent');this.advance();}
 legalEndings():Ending[]{return this.c.endings.filter(e=>e.conditions.every(q=>conditionOK(this.c,this.s,q)));}
 chooseEnding(id:string){if(this.s.phase!=='ending'||!this.legalEndings().some(e=>e.id===id))throw new Error('Ending unavailable');this.log('chooseEnding',id);this.s.endingId=id;this.s.phase='finished';}
 command(command:string,args:any[]){const actions:Record<string,(...a:any[])=>void>={enter:this.enter,finishBattle:this.finishBattle,reward:this.reward,skipReward:this.skipReward,replace:this.replace,cancelReplacement:this.cancelReplacement,buy:this.buy,refresh:this.refresh,leaveShop:this.leaveShop,rest:this.rest,chooseEvent:this.chooseEvent,leaveEvent:this.leaveEvent,chooseEnding:this.chooseEnding};if(!actions[command])throw new Error('Invalid command');actions[command].apply(this,args);}
}
export function replayRun(c:Content,source:RunState):RunState {const g=Game.create(c,source.seed,source.origin,source.fate,source.name,source.portrait);for(const a of source.actionLog)g.command(a.command,a.args);return g.s;}
'''
engine_path.write_text(ENGINE, encoding='utf-8')


def sub_once(pattern: str, replacement: str, text: str, label: str) -> str:
    out, count = re.subn(pattern, replacement, text, count=1, flags=re.S)
    if count != 1:
        raise RuntimeError(f'{label}: expected 1 replacement, got {count}')
    return out

app = app_path.read_text(encoding='utf-8')
if "hidden:'eye'" not in app:
    app = re.sub(r"(const NODE_ICONS:Record<string,string>=\{[^}]*)(boss:'gate')", r"\1hidden:'eye',\2", app, count=1)

new_map = r''' map(){const s=this.game!.s,a=this.content.acts[s.act],nodes=s.route.filter(n=>n.act===s.act),avail=this.game!.available().map(n=>n.id),x=(lane:number)=>[155,400,645][lane],y=(row:number)=>[710,586,465,345,223,93][row];let paths='';for(const n of nodes)for(const m of nodes.filter(m=>m.row===n.row+1&&Math.abs(m.lane-n.lane)<=1)){const done=s.visited.includes(n.id)&&s.visited.includes(m.id);paths+=`<path d="M${x(n.lane)} ${y(n.row)}C${x(n.lane)} ${y(n.row)-65} ${x(m.lane)} ${y(m.row)+65} ${x(m.lane)} ${y(m.row)}" fill="none" stroke="${done?'#d7bd7a':'#9b9e75'}" stroke-width="${done?2.3:1.3}" stroke-dasharray="${done?'none':'5 8'}" opacity="${done?.7:.32}"/>`;}const nodeLabel=(n:any)=>n.type==='hidden'?'未明':n.type==='boss'?this.content.enemies.find(e=>e.id===n.ref)!.name:(this.content.labels.nodes[n.type]??n.type);return `${this.heading(a.name,a.subtitle,a.chapter+' / CHAPTER '+(s.act+1))}<div class="map-wrap">${landscape()}<div class="map-watermark">${esc(a.name)}</div><svg class="map-lines" viewBox="0 0 800 840" preserveAspectRatio="none">${paths}</svg>${nodes.map(n=>`<button class="map-node ${n.type} ${avail.includes(n.id)?'available':''} ${s.visited.includes(n.id)?'done':''}" style="left:${x(n.lane)/8}%;top:${y(n.row)/8.4}%" data-action="enter" data-id="${n.id}" ${avail.includes(n.id)?'':'disabled'} aria-label="${esc(nodeLabel(n))}"><span class="node-disc">${icon(s.visited.includes(n.id)?'check':NODE_ICONS[n.type]??'eye')}</span><span class="node-label">${esc(nodeLabel(n))}</span></button>`).join('')}<div class="map-note"><span><span class="dot"></span>选择亮起的命途节点</span><span class="node-count">${String(s.act*6+s.row).padStart(2,'0')} / 24</span></div></div><div class="map-legend">${['combat','elite','event','hidden','shop','rest','major'].map(k=>`<span>${icon(NODE_ICONS[k]??'eye',14)}${esc(this.content.labels.nodes[k]??(k==='hidden'?'未明':k))}</span>`).join('')}</div>`;}'''
app = sub_once(r"\n map\(\)\{.*?\n card\(", "\n" + new_map + "\n card(", app, 'map')

battle_helpers = r''' battleLogRow(frame:Frame,index:number,frames:Frame[],enemyName:string){const prev=frames[Math.max(0,index-1)],actor=frame.actor==='p'?this.game!.s.name:frame.actor==='e'?enemyName:'天道',details:string[]=[];const delta=(label:string,before:number,after:number,cls:string)=>before===after?'':`<span class="log-delta ${cls}">${label} ${before}→${after} <b>${after-before>0?'+':''}${after-before}</b></span>`;for(const side of ['p','e'] as const){const before=prev[side],after=frame[side],who=side==='p'?this.game!.s.name:enemyName,changes:string[]=[];for(const x of [delta('生命',before.hp,after.hp,'hp'),delta('护盾',before.shield,after.shield,'shield'),delta('怒气',before.rage,after.rage,'rage')])if(x)changes.push(x);for(const k of new Set([...Object.keys(before.status),...Object.keys(after.status)])){const a=before.status[k]??0,b=after.status[k]??0;if(a!==b)changes.push(`<span class="log-delta status">${esc(this.content.labels.statuses[k]??k)} ${a}→${b} <b>${b-a>0?'+':''}${b-a}</b></span>`);}if(changes.length)details.push(`<div class="log-side"><em>${esc(who)}</em>${changes.join('')}</div>`);}const outcome=frame.kind==='damage'?`<span class="log-amount">${frame.crit?'暴击 · ':''}${frame.amount} 伤害</span>`:frame.kind==='miss'?'<span class="log-outcome">闪避</span>':frame.kind==='rage'?'<span class="log-outcome rage">怒气技</span>':frame.kind==='phase'?'<span class="log-outcome phase">阶段转换</span>':'';const b=frame.breakdown,formula=b?`<div class="combat-formula"><span>原始 ${b.base}</span><span>倍率后 ${b.scaled}</span><span>防御后 ${b.afterDefense}</span><span>易伤后 ${b.afterVulnerable}</span><span>暴击后 ${b.afterCrit}</span>${b.absorbed?`<span>护盾吸收 ${b.absorbed}</span>`:''}<b>生命损失 ${b.hpLoss}</b></div>`:'';return `<article class="battle-log-row kind-${frame.kind.replace(/[^a-z_-]/g,'')} ${frame.crit?'critical':''}"><div class="battle-log-main"><span class="round">${String(frame.round).padStart(2,'0')}</span><span class="log-actor">${esc(actor)}</span><strong>${esc(frame.label)}</strong>${outcome}</div>${frame.detail?`<div class="log-note">${esc(frame.detail)}</div>`:''}${formula}${details.length?`<div class="battle-log-detail">${details.join('')}</div>`:''}</article>`;}
 battle(){const b=this.game!.s.battle!,cursor=bi(b.cursor,0,b.frames.length-1),f=b.frames[cursor],done=cursor>=b.frames.length-1,enemy=this.content.enemies.find(e=>e.id===b.enemyId)!,sum=b.summary,obj=b.objective;return `${this.heading(done?(b.won?'此战告捷':'此身入劫'):'斗法','',enemy.kind==='boss'?'BOSS / HEAVENLY TRIAL':'ROUND '+String(f.round).padStart(2,'0'))}<div class="battle-objective"><div><span>斗法目标</span><strong>${esc(obj.label??obj.type)}</strong></div><div><span>敌方决策</span><strong>${enemy.ai==='weighted'?'权重择法':'贪心择法'}</strong></div>${obj.type==='survive'?`<div><span>坚持</span><strong>${obj.rounds} 回合</strong></div>`:obj.type==='break'?`<div><span>破阵</span><strong>${b.objectiveProgress} / ${obj.value}</strong></div>`:''}</div><div class="combat-arena">${landscape()}${this.fighterFrame(f,'p')}<div class="versus"><small>斗法</small>VS</div>${this.fighterFrame(f,'e')}${f.amount>0?`<div class="damage-number" key="${cursor}">${f.crit?'<small>暴击</small>':''}${f.amount}</div>`:''}</div><div class="battle-controls"><div class="speeds">${[1,2,4].map(n=>`<button class="${this.speed===n?'active':''}" data-action="speed" data-index="${n}" aria-label="${n}倍速">${n}×</button>`).join('')}<button data-action="pause" ${done?'disabled':''}>${this.paused?'继续':'暂停'}</button></div>${done?btn('finishBattle',b.won?'领取机缘 '+icon('arrow',16):'查看命途','primary small'):btn('skip','略过回放 '+icon('arrow',16),'small')}</div>${done?`<div class="battle-summary"><div><span>造成伤害</span><b>${sum.playerDamage}</b></div><div><span>承受伤害</span><b>${sum.enemyDamage}</b></div><div><span>护盾承伤</span><b>${sum.playerShieldAbsorbed}</b></div><div><span>暴击 / 闪避</span><b>${sum.playerCrits} / ${sum.enemyMisses}</b></div><div><span>怒气技</span><b>${sum.playerRageSkills}</b></div><div><span>状态结算</span><b>${sum.statusTicks}</b></div>${sum.phaseChanges?`<div><span>Boss 变相</span><b>${sum.phaseChanges}</b></div>`:''}</div>`:''}<div class="battle-log-head"><span>斗法战报</span><small>${cursor+1} / ${b.frames.length} · 最新在上</small></div><div class="battle-log" aria-live="polite" tabindex="0">${b.frames.slice(0,cursor+1).map((row,i)=>this.battleLogRow(row,i,b.frames,enemy.name)).reverse().join('')}</div><p class="battle-caption">${esc(enemy.intent)}</p>`;}'''
app = sub_once(r"\n battleLogRow\(.*?\n event\(\)", "\n" + battle_helpers + "\n event()", app, 'battle')

new_event = r''' event(){const s=this.game!.s,event=this.content.events.find(e=>e.id===s.eventId)!,phase=this.game!.eventPhase(),options=this.game!.eventChoices();const check=s.lastCheck;return `<section class="event-page"><div class="event-portrait">${portrait(event.art)}</div><div class="eyebrow">${event.major?'A TURN OF FATE':s.current?.type==='hidden'?'THE UNKNOWN':'AN ENCOUNTER'} / ${esc(event.npc)}</div><h2>${esc(event.name)}</h2><div class="event-phase-mark"><span>${event.phases?.length?'阶段 '+String((s.eventStep??0)+1).padStart(2,'0'):'因缘'}</span><strong>${esc(phase.id==='root'?'抉择':phase.id)}</strong></div>${ornament()}${s.phase==='event'&&s.resultText?`<div class="event-outcome compact">${check?`<b class="${check.success?'success':'failure'}">${check.success?'检定成功':'检定失败'} · ${check.roll}/${check.chance}</b>`:''}<span>${esc(s.resultText)}</span></div>`:''}<p class="story-text">${esc(phase.text)}</p>${s.phase==='event'?`<div class="story-choices">${options.map(info=>{const ch=info.choice;return `<button class="story-choice ${ch.check?'checked-choice':''}" data-action="event" data-id="${ch.id}" ${info.legal?'':'disabled'}><div><strong>${esc(ch.label)}</strong><p>${esc(ch.preview??ch.text)}${info.legal?'':' （条件未达成）'}</p>${ch.check?`<span class="check-badge">${esc(this.content.labels.stats[ch.check.stat])}检定 · ${info.chance}%</span>`:''}</div>${icon('arrow',22)}</button>`;}).join('')}</div>`:`<div class="event-result">${check?`<div class="check-result ${check.success?'success':'failure'}"><strong>${check.success?'检定成功':'检定失败'}</strong><span>${esc(this.content.labels.stats[check.stat])} · ${check.roll} / ${check.chance}</span></div>`:''}${esc(s.resultText??'')}</div><div class="actions">${btn('leaveEvent','记下此因，继续前行 '+icon('arrow',18),'primary')}</div>`}</section>`;}'''
app = sub_once(r"\n event\(\)\{.*?\n shop\(\)", "\n" + new_event + "\n shop()", app, 'event')

new_shop = r''' shop(){const s=this.game!.s,count=s.refreshes[s.act],price=this.content.rules.refreshPrices[count];const offer=(o:any,i:number)=>o.kind==='ability'?this.card(o.id!,s.slots.find(e=>e?.id===o.id)?.rank??0,'buy',`data-index="${i}" ${o.sold||s.gold<o.price?'disabled':''}`,icon('coin',14)+` ${o.price}`):o.kind==='heal'?`<button class="ability-card shield" data-action="buy" data-index="${i}" ${o.sold||s.gold<o.price?'disabled':''}><div class="card-top"><span>调息 / 即时</span><span class="card-rank">+</span></div>${sigil('gourd','shield')}<h3 class="card-title">玉露琼浆</h3><p class="card-description">恢复 30% 最大生命。</p><div class="card-foot"><span>恢复生命</span><span class="gain">${icon('coin',14)} ${o.price}</span></div></button>`:`<button class="ability-card jade" data-action="buy" data-index="${i}" ${o.sold||s.gold<o.price?'disabled':''}><div class="card-top"><span>淬炼 / 即时</span><span class="card-rank">+</span></div>${sigil(STAT_ICONS[o.stat]??'star','jade')}<h3 class="card-title">${esc(this.content.labels.stats[o.stat])}淬炼</h3><p class="card-description">本局 ${esc(this.content.labels.stats[o.stat])} +${o.value}。</p><div class="card-foot"><span>即时生效</span><span class="gain">${icon('coin',14)} ${o.price}</span></div></button>`;return `${this.heading('云游坊市','天下宝物，皆有其价。','THE WANDERING MARKET')}<div class="shop-balance"><span>${icon('coin',18)} 灵石 <strong class="gold">${s.gold}</strong></span><span class="muted">本幕刷新 ${count} / 3</span></div><div class="shop-grid">${s.stock.map((o,i)=>`<div style="position:relative">${offer(o,i)}${o.sold?'<div class="sold-label">已售出</div>':''}</div>`).join('')}</div><div class="actions">${btn('refresh',price===undefined?'本幕刷新已尽':price===0?'免费刷新':'刷新  '+price+' 灵石','',price===undefined||s.gold<price?'disabled':'')}${btn('leaveShop','离开坊市 '+icon('arrow',18),'primary')}</div>`;}'''
app = sub_once(r"\n shop\(\)\{.*?\n rest\(\)", "\n" + new_shop + "\n rest()", app, 'shop')

new_karma = r''' karma(){const s=this.game!.s;return `${this.heading('因果簿','', 'THE THREADS OF FATE')}<div class="karma-grid">${Object.entries(this.content.labels.counters).map(([k,n])=>`<div class="karma-counter"><strong>${s.counters[k]??0}</strong><p>${esc(n)}</p></div>`).join('')}</div><div class="build-tags">${Object.keys(s.facts).filter(k=>s.facts[k]).map(k=>`<span>${esc(this.content.labels.facts[k]??k)}</span>`).join('')}</div>${Object.keys(s.threads).length?`<div class="thread-grid">${Object.entries(s.threads).map(([k,v])=>`<div><span>${esc(k.replaceAll('_',' '))}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`:''}${s.storyLog.length?`<div class="timeline">${s.storyLog.map(l=>`<div class="timeline-item"><span class="eyebrow" style="font-size:8px">${esc(this.content.acts[l.act].chapter)}${l.phase?' · '+esc(l.phase):''}</span><h3>${esc(l.title)}</h3><p>${esc(l.choice)}${l.chance?` · 检定 ${l.roll}/${l.chance} ${l.success?'成功':'失败'}`:''}</p>${l.result?`<small>${esc(l.result)}</small>`:''}</div>`).join('')}</div>`:'<div class="empty-note">还没有写下因果。</div>'}<div class="panel panel-body" style="margin-top:25px"><div class="eyebrow">POSSIBLE ENDINGS</div><p class="small muted" style="margin-top:10px;line-height:2">榜上有名：阐教≥ 2 · 肉身成道：善念≥ 3<br>逆命而行：逆命≥ 5 · 方外散仙：通关可选</p></div>`;}'''
app = sub_once(r"\n karma\(\)\{.*?\n endings\(\)", "\n" + new_karma + "\n endings()", app, 'karma')

new_final = r''' final(){const s=this.game!.s,ending=this.content.endings.find(e=>e.id===s.endingId),dead=s.phase==='dead',echoes=Object.entries(s.threads).filter(([k])=>k.startsWith('act_'));return `<section class="final-page"><div class="eyebrow">${dead?'THIS IS NOT THE END':'A NAME BEYOND THE SCROLL'}</div><div class="final-seal">${icon(dead?'moon':ending?.art??'seal',68)}</div><h1>${dead?'劫中归寂':esc(ending!.name)}</h1><p>${dead?'此身虽散，道心未灭。':esc(ending!.description)}</p>${echoes.length?`<div class="final-echoes"><span>四幕回响</span>${echoes.map(([k,v])=>`<b>${esc(k.replace('act_','第 ').replace('_fate',' 幕'))} · ${esc(v)}</b>`).join('')}</div>`:''}<div class="final-stats"><div><strong>${s.visited.length} / 24</strong>走过节点</div><div><strong>${this.content.realms[s.level]}</strong>最终境界</div><div><strong>${s.hp}</strong>剩余生命</div></div><p class="mono" style="font-size:10px">SEED ${esc(s.seed)} / CONTENT ${esc(s.version)}</p><div class="actions">${btn('new','再入一场大劫','primary')}${btn('export','导出命途','')}</div></section>`;}'''
app = sub_once(r"\n final\(\)\{.*?\n stage\(\)", "\n" + new_final + "\n stage()", app, 'final')

# Remove the loud technical guidance left in the older bootstrap source.
app = re.sub(r'<p class="start-note">.*?</p>', '<p class="start-note">天命未定 · 八槽成局</p>', app, count=1, flags=re.S)
app_path.write_text(app, encoding='utf-8')

css = css_path.read_text(encoding='utf-8')
marker = '/* Gameplay v3: ssxx2-derived systems */'
if marker not in css:
    css += r'''

/* Gameplay v3: ssxx2-derived systems */
.map-node.hidden .node-disc{border-style:dashed;background:radial-gradient(circle,#443d58,#151d23);box-shadow:0 0 18px #8b70b64a}.map-node.hidden.available .node-disc{animation:hiddenPulse 2.3s ease-in-out infinite}.map-node.hidden .node-label{letter-spacing:3px;color:#bca9d2}@keyframes hiddenPulse{50%{filter:brightness(1.35);transform:scale(1.06)}}
.battle-objective{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin:0 auto 12px;max-width:760px}.battle-objective>div{padding:8px 10px;border:1px solid #a89a6838;background:#101b19;display:flex;align-items:center;justify-content:space-between;gap:8px}.battle-objective span{font-size:9px;letter-spacing:1.2px;color:var(--muted)}.battle-objective strong{font-size:11px;color:#e2d7b1}
.battle-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;max-width:760px;margin:12px auto}.battle-summary>div{border:1px solid #93a68b2e;background:#15211d;padding:7px 8px;display:flex;justify-content:space-between}.battle-summary span{font-size:9px;color:var(--muted)}.battle-summary b{font-size:13px;color:#ddd4b6}
.log-note{margin:4px 0 0 74px;font-size:9px;color:#8ca399}.combat-formula{display:flex;flex-wrap:wrap;gap:5px;margin:6px 0 2px 74px}.combat-formula span,.combat-formula b{font-size:8px;padding:2px 5px;border:1px solid #91a98f2d;background:#10201c}.combat-formula b{color:#e2c486}.log-outcome.phase{color:#c6a8df;border-color:#8b69aa55}.kind-phase{border-left:2px solid #8b69aa!important;background:linear-gradient(90deg,#402c4f26,transparent)!important}
.event-phase-mark{display:inline-flex;gap:8px;align-items:center;margin-top:2px;padding:4px 9px;border:1px solid #af966c34;background:#14201d}.event-phase-mark span{font-size:8px;color:var(--muted);letter-spacing:1px}.event-phase-mark strong{font-size:9px;color:#d7c69d}.event-outcome.compact{display:flex;flex-direction:column;gap:5px;max-width:650px;margin:12px auto;padding:10px 13px;border-left:2px solid #9d895b;background:#17221e;text-align:left}.event-outcome.compact b{font-size:9px;letter-spacing:1px}.event-outcome.compact .success,.check-result.success strong{color:#8fc59c}.event-outcome.compact .failure,.check-result.failure strong{color:#d58a7e}.check-badge{display:inline-block;margin-top:7px;padding:3px 7px;border:1px solid #c2a76555;background:#241f17;color:#d9bf7a;font-size:8px;letter-spacing:1px}.checked-choice{position:relative}.check-result{display:flex;justify-content:space-between;gap:12px;margin-bottom:10px;padding-bottom:9px;border-bottom:1px solid var(--line);font-size:10px}.check-result span{color:var(--muted)}
.thread-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:16px 0}.thread-grid>div{display:flex;justify-content:space-between;gap:8px;padding:8px 10px;border:1px solid #8fa08e32;background:#13201c}.thread-grid span{font-size:9px;color:var(--muted);text-transform:uppercase}.thread-grid strong{font-size:10px;color:#d7c69d}.timeline-item small{display:block;margin-top:5px;color:#899c92;line-height:1.55}.final-echoes{display:flex;flex-wrap:wrap;justify-content:center;gap:6px;margin:15px auto;max-width:650px}.final-echoes>span{width:100%;font-size:9px;letter-spacing:2px;color:var(--muted)}.final-echoes b{padding:5px 8px;border:1px solid #a28b5d44;background:#171f1c;font-size:9px;font-weight:500;color:#d4c49d}
@media(max-width:760px){.battle-objective{grid-template-columns:1fr 1fr}.battle-summary{grid-template-columns:1fr 1fr}.log-note,.combat-formula{margin-left:0}.thread-grid{grid-template-columns:1fr}}
'''
css_path.write_text(css, encoding='utf-8')

script = gen_path.read_text(encoding='utf-8')
anchor = "assert len(A)==43 and len(E)==20 and len(C['events'])==16"
if '# Gameplay v3 content enrichment' not in script:
    if anchor not in script:
        raise RuntimeError('content assert anchor not found')
    enrich = r'''# Gameplay v3 content enrichment: event phases/checks, occurrence profiles, combat AI/objectives/phases.
C['version']='2.0.0'
C['rulesVersion']='2.0.0'
C['labels']['nodes']['hidden']='未明'
for a in C['abilities']:
 a['cooldown']=0
 a['priority']=20 if a['slot']=='rage' else 10 if a['slot']=='basic' else 0
for aid,cd in {'rage.army':2,'rage.sky':1,'rage.lotus':1}.items():
 next(x for x in C['abilities'] if x['id']==aid)['cooldown']=cd
for enemy in C['enemies']:
 act=enemy['act'];enemy['ai']='weighted' if int(enemy['id'].split('.')[-1])%2 else 'greedy';enemy['objective']={'type':'kill','label':'击破敌身'}
 if enemy['kind']=='elite':
  enemy['objective']={'type':'survive','rounds':4+act,'label':f'撑过 {4+act} 回合'} if act%2==0 else {'type':'break','value':55+act*20,'label':'击破护阵'}
 if enemy['kind']=='boss':
  enemy['phases']=[{'hpPercent':60,'label':'劫相·变阵','effects':[dict(type='gain_shield',target='self',value=8+act*4,stat='defense',coefficient=80)]},{'hpPercent':30,'label':'劫相·压境','effects':[dict(type='gain_rage',target='self',value=30),dict(type='modify_stat',target='self',stat='attack',percent=15,value=0)]}]
for ev in C['events']:
 ev['profile']='A' if ev['major'] or not ev['id'].endswith('.hermit') else 'B';ev['weight']=2 if ev['id'].endswith('.ruins') else 1;ev['maxPerRun']=2 if ev['profile']=='B' else 1
 if ev['major']:
  for ch in ev['choices']:
   fact=f"major_{ev['act']}_{ch['id']}";ch['effects'].append(eff('set_fact',key=fact,value=True));ch['effects'].append(eff('advance_thread',key=f"act_{ev['act']}_fate",value=ch['id']));C['labels']['facts'][fact]=f"{ev['name']}·{ch['label']}"

def branch(text,effects,grant=None,next=None):
 d=dict(text=text,effects=effects)
 if grant is not None:d['grant']=grant
 if next is not None:d['next']=next
 return d

def phase_choice(id,label,preview,effects=None,conditions=None,next=None,check=None):
 d=dict(id=id,label=label,text=preview,preview=preview,effects=effects or [],grant=None,conditions=conditions or [])
 if next is not None:d['next']=next
 if check is not None:d['check']=check
 return d

omens=['荒祠夜签','海眼残碑','岐山断阵','万仙余烬']
omens_npc=['无面庙祝','巡海夜叉','阵中残魂','劫后散仙']
echo_names=['旧誓回声','龙潮旧债','西岐故人','榜外来客']
major_first=['save','nezha','chan','accept']
extra=[]
for act in range(4):
 diff=12+act*3
 inspect_check=dict(stat='attack',base=48,difficulty=diff,success=branch('你看穿阵纹，借其余势淬炼己身。',[eff('gain_xp',value=22+act*4),eff('modify_stat',stat='attack',value=2)]),failure=branch('阵纹反噬，经脉一阵灼痛。',[eff('damage',value=7+act*3),eff('add_counter',key='defiance',value=1)]))
 luck_check=dict(stat='luck',base=45,difficulty=10+act*2,success=branch('暗格应声而开，灵石与旧简一并落入掌中。',[eff('gain_currency',value=28+act*8),eff('gain_xp',value=12)]),failure=branch('机关早已朽坏，只余一缕劫气。',[eff('damage',value=4+act*2)]))
 extra.append(dict(id=f'event.{act}.omen',act=act,major=False,name=omens[act],npc=omens_npc[act],art='seal',text='旧物不语，因果自鸣。',choices=[],profile='A',weight=2,maxPerRun=1,startPhase='threshold',phases=[dict(id='threshold',text='残破石门后有微光游走。你可以循迹深入，也可以把这段因果留在身后。',choices=[phase_choice('enter','循光深入','进入下一重迹象。',next='core'),phase_choice('leave','转身离开','不涉险，调息片刻。',[eff('heal',value=8+act*2)])]),dict(id='core',text='阵心只余两处尚可触碰：一道以力破之，一道凭机缘寻隙。',choices=[phase_choice('force','以力破阵','公开攻击检定；成功可获得修为并淬炼攻击。',check=inspect_check),phase_choice('read','顺势寻隙','公开气运检定；成功可获得灵石。',check=luck_check)])]))
 prev_key=f"major_{act-1}_{major_first[act-1]}" if act>0 else None
 echo_choices=[phase_choice('steady','守心而过','恢复少量生命，善念 +1。',[eff('heal',value=10+act*3),eff('add_counter',key='mercy',value=1)]),phase_choice('seize','截取余势','获得灵石，但逆命 +1。',[eff('gain_currency',value=20+act*7),eff('add_counter',key='defiance',value=1)])]
 if prev_key: echo_choices.insert(0,phase_choice('remember','追索旧因','只有曾走过对应旧路时才能选择；将旧因推进为新的因果线。',[eff('gain_xp',value=30),eff('modify_stat',stat='luck',value=2),eff('advance_thread',key=f'echo_{act}',value=prev_key)],conditions=[cond('has_fact',key=prev_key)]))
 else: echo_choices.insert(0,phase_choice('remember','记住此地','把这场相逢写入因果。',[eff('gain_xp',value=20),eff('advance_thread',key='echo_0',value='remembered')]))
 extra.append(dict(id=f'event.{act}.echo',act=act,major=False,name=echo_names[act],npc='因果余音',art='hermit',text='前路忽然与旧路重叠。',choices=echo_choices,profile='A',weight=1,maxPerRun=1))
C['events'].extend(extra)
'''
    script = script.replace(anchor, enrich + "\nassert len(A)==43 and len(E)==20 and len(C['events'])==24")
gen_path.write_text(script, encoding='utf-8')

policy = r'''import {Game,fateOptions,SLOT_ORDER} from '../build/engine.js';
export function score(g,id,rank=0){const a=g.ability(id),aff=g.c.origins.find(o=>o.id===g.s.origin).affinity;return (a.tags.includes(aff)?10:0)+(a.rarity==='mythic'?18:a.rarity==='rare'?3:0)+rank*4+Object.values(a.stats).reduce((sum,v)=>sum+(Array.isArray(v)?v[rank]:v)*.35,0);}
export function gain(g,id){const a=g.ability(id),eq=g.s.slots.find(x=>x?.id===id);if(eq)return eq.rank<3?7:-999;const matching=SLOT_ORDER.map((k,i)=>k===a.slot?i:-1).filter(i=>i>=0);if(matching.some(i=>!g.s.slots[i]))return 20+score(g,id);return score(g,id)-Math.min(...matching.map(i=>score(g,g.s.slots[i].id,g.s.slots[i].rank)));}
function eventValue(g,info){const ch=info.choice,hp=g.s.hp/g.stats().hp;let v=(info.chance??60)/20;for(const e of ch.effects??[])v+=e.type==='heal'?(hp<.8?40:8):e.type==='modify_stat'?e.stat==='attack'?15:e.stat==='defense'?18:4:e.type==='gain_xp'?5:e.type==='damage'?-15:e.type==='gain_currency'?6:0;if(ch.grant?.id)v+=Math.max(0,gain(g,ch.grant.id));else if(ch.grant)v+=10;return v;}
export function step(g){const s=g.s,c=g.c,hp=s.hp/g.stats().hp;
 if(s.pending){const p=s.pending,a=g.ability(p.id),candidates=SLOT_ORDER.map((k,i)=>k===a.slot?i:-1).filter(i=>i>=0).sort((i,j)=>score(g,s.slots[i].id,s.slots[i].rank)-score(g,s.slots[j].id,s.slots[j].rank));if(gain(g,p.id)>0)g.replace(candidates[0]);else{g.cancelReplacement();if(s.phase==='reward')g.skipReward();else if(s.phase==='shop')g.leaveShop();}return;}
 switch(s.phase){case 'map':{const weight={combat:3,event:9,hidden:10,rest:hp<.85?20:7,shop:s.gold>=25&&hp<.75?15:4,elite:hp>.8?12:1,major:10,boss:10};g.enter(g.available().sort((a,b)=>(weight[b.type]??0)-(weight[a.type]??0))[0].id);break;}case 'battle':g.finishBattle();break;case 'reward':{const ix=s.reward.map((id,i)=>({i,v:gain(g,id)})).sort((a,b)=>b.v-a.v)[0];if(ix?.v>0)g.reward(ix.i);else g.skipReward();break;}case 'shop':{const offers=s.stock.map((o,i)=>({i,v:o.sold||o.price>s.gold?-999:o.kind==='heal'?(hp<.85?50:-1):o.kind==='stat'?12:gain(g,o.id)})).sort((a,b)=>b.v-a.v);if(offers[0]?.v>0)g.buy(offers[0].i);else g.leaveShop();break;}case 'rest':if(hp<.86)g.rest('heal');else{const eq=s.slots.map((x,i)=>({x,i})).filter(o=>o.x&&o.x.rank<3).sort((a,b)=>score(g,b.x.id)-score(g,a.x.id))[0];if(eq)g.rest(g.ability(eq.x.id).slot==='artifact'?'artifact':'skill',eq.i);else g.rest('temper',0);}break;case 'event':{const opts=g.eventChoices().filter(x=>x.legal).map(x=>({x,v:eventValue(g,x)})).sort((a,b)=>b.v-a.v);if(!opts.length)throw new Error('No legal event choice');g.chooseEvent(opts[0].x.choice.id);break;}case 'event_result':g.leaveEvent();break;case 'ending':g.chooseEnding(g.legalEndings()[0].id);break;}
}
export function run(c,origin,seed,max=400){const fate=fateOptions(c,seed).sort((a,b)=>Object.keys(b.percent??{}).length-Object.keys(a.percent??{}).length)[0],g=Game.create(c,seed,origin,fate.id,'Sim');let decisions=0;while(!['dead','finished'].includes(g.s.phase)&&decisions++<max)step(g);if(decisions>=max)throw new Error('Non-terminating run');return g;}
'''
policy_path.write_text(policy, encoding='utf-8')

tests = test_path.read_text(encoding='utf-8').replace("assert.equal(c.events.length,16)", "assert.equal(c.events.length,24)")
if "event check preview never consumes RNG" not in tests:
    tests += r'''

test('event check preview never consumes RNG and exposes public probability',()=>{const g=fresh('CHECK-PREVIEW'),ev=c.events.find(e=>e.phases?.some(p=>p.choices.some(ch=>ch.check)));g.s.phase='event';g.s.eventId=ev.id;g.s.eventPhase=ev.startPhase;g.s.seenEvents[ev.id]=1;const first=g.eventChoices().find(x=>x.choice.next);g.chooseEvent(first.choice.id);const before=clone(g.s.rng),a=g.eventChoices().find(x=>x.choice.check),b=g.eventChoices().find(x=>x.choice.id===a.choice.id);assert.equal(a.chance,b.chance);assert(a.chance>=10&&a.chance<=95);assert.deepEqual(g.s.rng,before);});
test('event checks are deterministic under the same seed and action sequence',()=>{const play=()=>{const g=fresh('CHECK-SAME'),ev=c.events.find(e=>e.id==='event.0.omen');g.s.phase='event';g.s.eventId=ev.id;g.s.eventPhase=ev.startPhase;g.s.seenEvents[ev.id]=1;g.chooseEvent('enter');g.chooseEvent('force');return clone(g.s.lastCheck);};assert.deepEqual(play(),play());});
test('event occurrence contracts and hidden limit are enforced while planning route',()=>{for(let i=0;i<20;i++){const g=fresh('ROUTE-'+i);for(let act=0;act<4;act++){const refs=g.s.route.filter(n=>n.act===act&&['event','hidden'].includes(n.type)).map(n=>n.ref);for(const id of new Set(refs)){const ev=c.events.find(e=>e.id===id),count=refs.filter(x=>x===id).length;assert(count<=(ev.profile==='B'?2:1));}assert(g.s.route.filter(n=>n.act===act&&n.type==='hidden').length<=1);}}});
test('combat uses separated RNG domains and boss phase transitions are typed frames',()=>{const g=fresh('BOSS-PHASE');g.s.bonus.attack=250;g.s.bonus.hp=300;const boss=c.enemies.find(e=>e.kind==='boss'),b=simulateBattle(c,g.s,boss);assert(Object.keys(g.s.rng).some(k=>k.includes('.hit')));assert(Object.keys(g.s.rng).some(k=>k.includes('.crit')));assert(b.frames.some(f=>f.kind==='phase'));assert(b.summary.phaseChanges>=1);});
test('non-kill objectives can complete without forcing enemy HP to zero',()=>{const g=fresh('OBJECTIVE');g.s.bonus.hp=500;g.s.bonus.defense=150;const enemy=c.enemies.find(e=>e.objective?.type==='survive'),b=simulateBattle(c,g.s,enemy);assert.equal(b.won,true);assert(b.e??true);assert(b.frames.at(-1).objective);});
test('shop contains mixed ability recovery and attribute stock',()=>{const g=fresh('SHOP-MIX');g.s.phase='shop';g.rollShop();assert(g.s.stock.some(x=>x.kind==='ability'));assert(g.s.stock.some(x=>x.kind==='heal'));assert(g.s.stock.some(x=>x.kind==='stat'));});
'''
test_path.write_text(tests, encoding='utf-8')

doc_path.write_text('''# Gameplay V3\n\nThis revision adapts gameplay architecture from `ssxx2/dev` CORE_GAMEPLAY and ENGINE_CAPABILITIES to the current browser game.\n\n- Deterministic RNG is split by route, event checks, enemy AI, hit, crit and trigger domains.\n- Combat remains fully automatic; build selection is the player's battle intent. Main actions are resolved through a legal-action selector with cooldown and enemy greedy/weighted AI.\n- Encounters may use kill, survive or break objectives. Bosses can transition through deterministic HP phases.\n- Combat emits typed replay frames with damage-pipeline breakdown and battle summary.\n- Events support 2-4 choices per phase, up to five phases, public attribute-check probability, confirm-time RNG only, occurrence profiles/weights and cross-act fact/thread echoes.\n- One hidden route node may appear per act without revealing its event before entry.\n- Shop stock mixes build options, recovery and immediate attribute growth. Rest remains a one-of-four preparation decision.\n- The current game intentionally retains the merged seven-stat model (HP, attack, defense, speed, hit, dodge, luck) rather than restoring ssxx2's split physical/magical panel.\n''', encoding='utf-8')

print('Gameplay V3 patch applied')
